#!/bin/bash
# set -e

if [ -z "$1" ]; then
    echo "Usage: $0 <version> (ex: 3.8.3)"
    exit 1
fi

VERSION="$1"
NEW_DIR="qualcoder-${VERSION}"

# Compile QualCoder
python3 -m venv ".env"
source .env/bin/activate
python3 -m pip install --upgrade pip
pip install -r requirements.txt
pyinstaller qualcoder_onefile.spec
deactivate

#  Create .deb
echo "Copy template ${NEW_DIR}..."
cp -r "qualcoder-debian" "$NEW_DIR"

mkdir -p "${NEW_DIR}/src"
cp "dist/QualCoder" "${NEW_DIR}/src/qualcoder"
chmod +x "${NEW_DIR}/src/qualcoder"


echo "Update changelog ..."
cat > "${NEW_DIR}/debian/changelog" << EOF
qualcoder (${VERSION}) UNRELEASED; urgency=medium

  * New upstream release ${VERSION}.
  * See https://github.com/ccbogel/QualCoder/releases/tag/${VERSION}

 -- QualCoder Team <contact@qualcoder.org>  $(date -R)
EOF

sed -i "s/Standards-Version:.*/Standards-Version: ${VERSION}/" "${NEW_DIR}/debian/control"

mkdir -p "${NEW_DIR}/usr/share/man/man1"
cat > "${NEW_DIR}/usr/share/man/man1/qualcoder.1" << 'EOF'
.TH QUALCODER 1
.SH NAME
qualcoder \- Qualitative Data Analysis Tool
.SH SYNOPSIS
.B qualcoder
.SH DESCRIPTION
QualCoder is a free and open-source Computer Assisted Qualitative Data Analysis Software (CAQDAS) for coding qualitative data such as text, images, and audio/video.
.SH OPTIONS
There are no command-line options. QualCoder is a graphical application.
.SH AUTHOR
QualCoder Team <contact@qualcoder.org>
.SH SEE ALSO
.BR https://github.com/ccbogel/QualCoder
EOF

cat > "${NEW_DIR}/debian/rules" << 'EOF'
#!/usr/bin/make -f
%:
    dh $@

override_dh_auto_install:
    install -D -m 755 src/qualcoder debian/qualcoder/usr/bin/qualcoder
    install -D -m 644 usr/share/applications/QualCoder.desktop debian/qualcoder/usr/share/applications/QualCoder.desktop
    install -D -m 644 usr/share/icons/qualcoder.xpm debian/qualcoder/usr/share/icons/qualcoder.xpm
    install -D -m 644 usr/share/man/man1/qualcoder.1 debian/qualcoder/usr/share/man/man1/qualcoder.1
EOF

echo "Build version ${VERSION}..."
cd "$NEW_DIR"
debuild -us -uc
cd ..

echo "Package released : qualcoder_${VERSION}_amd64.deb"#!/bin/bash
set -e  # Exit on first error

# Check for required dependencies
for cmd in dpkg-dev debuild fakeroot upx-ucl python3 python3-venv lintian; do
    if ! command -v $cmd >/dev/null 2>&1; then
        echo "Error: $cmd is required but not installed."
        echo "Install it with: sudo apt install $cmd"
        exit 1
    fi
done

# Check command line argument
if [ -z "$1" ]; then
    echo "Usage: $0 <version> (e.g.: 4.0-beta)"
    exit 1
fi

VERSION="$1"
NEW_DIR="qualcoder-${VERSION}"

# Create virtual environment and compile
echo "Compiling QualCoder..."
python3 -m venv ".env"
source .env/bin/activate
python3 -m pip install --upgrade pip
pip install -r requirements.txt
pyinstaller qualcoder_onefile.spec --upx-dir=/usr/bin/upx
deactivate

# Verify the binary was created
if [ ! -f "dist/QualCoder" ]; then
    echo "Error: dist/QualCoder was not generated by PyInstaller"
    exit 1
fi

# Prepare Debian package structure
echo "Preparing Debian package structure..."
cp -r "qualcoder-debian" "${NEW_DIR}"
mkdir -p "${NEW_DIR}/src"
cp "dist/QualCoder" "${NEW_DIR}/src/qualcoder"
chmod +x "${NEW_DIR}/src/qualcoder"

# Update changelog with valid date
echo "Updating changelog..."
cat > "${NEW_DIR}/debian/changelog" << EOF
qualcoder (${VERSION}-1) UNRELEASED; urgency=medium

  * New upstream release ${VERSION}.
  * See https://github.com/ccbogel/QualCoder/releases/tag/${VERSION}

 -- QualCoder Team <contact@qualcoder.org>  $(date -R)
EOF

# Fix Standards-Version (must be a valid Debian version, not the software version)
echo "Fixing Standards-Version..."
sed -i "s/Standards-Version:.*/Standards-Version: 4.6.2/" "${NEW_DIR}/debian/control"

# Build the Debian package
echo "Building Debian package..."
cd "${NEW_DIR}"
debuild -us -uc
cd ..

# Result
lintian qualcoder_${VERSION}_amd64.deb
echo "Package released : qualcoder_${VERSION}_amd64.deb"
