# Form implementation generated from reading ui file 'GUI_UIs\ui_ai_chat.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_ai_chat(object):
    def setupUi(self, Dialog_ai_chat):
        Dialog_ai_chat.setObjectName("Dialog_ai_chat")
        Dialog_ai_chat.resize(946, 579)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog_ai_chat.sizePolicy().hasHeightForWidth())
        Dialog_ai_chat.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(Dialog_ai_chat)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_question = QtWidgets.QPushButton(parent=Dialog_ai_chat)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_question.sizePolicy().hasHeightForWidth())
        self.pushButton_question.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.pushButton_question.setFont(font)
        self.pushButton_question.setFlat(False)
        self.pushButton_question.setObjectName("pushButton_question")
        self.gridLayout.addWidget(self.pushButton_question, 1, 1, 1, 1)
        self.plainTextEdit_question = QtWidgets.QPlainTextEdit(parent=Dialog_ai_chat)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_question.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_question.setSizePolicy(sizePolicy)
        self.plainTextEdit_question.setMaximumSize(QtCore.QSize(16777215, 80))
        self.plainTextEdit_question.setPlainText("")
        self.plainTextEdit_question.setPlaceholderText("")
        self.plainTextEdit_question.setObjectName("plainTextEdit_question")
        self.gridLayout.addWidget(self.plainTextEdit_question, 1, 0, 1, 1)
        self.scrollArea_ai_output = QtWidgets.QScrollArea(parent=Dialog_ai_chat)
        self.scrollArea_ai_output.setStyleSheet("")
        self.scrollArea_ai_output.setWidgetResizable(True)
        self.scrollArea_ai_output.setObjectName("scrollArea_ai_output")
        self.scrollArea_ai_output_contents = QtWidgets.QWidget()
        self.scrollArea_ai_output_contents.setGeometry(QtCore.QRect(0, 0, 926, 473))
        # self.scrollArea_ai_output_contents.setStyleSheet("background-color: white;")
        self.scrollArea_ai_output_contents.setObjectName("scrollArea_ai_output_contents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollArea_ai_output_contents)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ai_output = QtWidgets.QLabel(parent=self.scrollArea_ai_output_contents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ai_output.sizePolicy().hasHeightForWidth())
        self.ai_output.setSizePolicy(sizePolicy)
        self.ai_output.setAutoFillBackground(False)
        # self.ai_output.setStyleSheet("background-color: white;")
        self.ai_output.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.ai_output.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.ai_output.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.ai_output.setText("")
        self.ai_output.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.ai_output.setScaledContents(False)
        self.ai_output.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.ai_output.setWordWrap(True)
        self.ai_output.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByKeyboard|QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse|QtCore.Qt.TextInteractionFlag.TextBrowserInteraction|QtCore.Qt.TextInteractionFlag.TextSelectableByKeyboard|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.ai_output.setObjectName("ai_output")
        self.verticalLayout.addWidget(self.ai_output)
        self.scrollArea_ai_output.setWidget(self.scrollArea_ai_output_contents)
        self.gridLayout.addWidget(self.scrollArea_ai_output, 0, 0, 1, 2)

        self.retranslateUi(Dialog_ai_chat)
        QtCore.QMetaObject.connectSlotsByName(Dialog_ai_chat)

    def retranslateUi(self, Dialog_ai_chat):
        _translate = QtCore.QCoreApplication.translate
        Dialog_ai_chat.setWindowTitle(_translate("Dialog_ai_chat", "AI Chat"))
        self.pushButton_question.setText(_translate("Dialog_ai_chat", ">"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_ai_chat = QtWidgets.QDialog()
    ui = Ui_Dialog_ai_chat()
    ui.setupUi(Dialog_ai_chat)
    Dialog_ai_chat.show()
    sys.exit(app.exec())
