# Form implementation generated from reading ui file 'ui_dialog_manage_links.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_manage_links(object):
    def setupUi(self, Dialog_manage_links):
        Dialog_manage_links.setObjectName("Dialog_manage_links")
        Dialog_manage_links.resize(794, 560)
        self.gridLayout = QtWidgets.QGridLayout(Dialog_manage_links)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(parent=Dialog_manage_links)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=Dialog_manage_links)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(parent=Dialog_manage_links)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 35))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 10))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_1 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_1.setGeometry(QtCore.QRect(0, 0, 441, 16))
        self.label_1.setObjectName("label_1")
        self.pushButton_search_folders = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_search_folders.setGeometry(QtCore.QRect(480, 0, 171, 28))
        self.pushButton_search_folders.setObjectName("pushButton_search_folders")
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)

        self.retranslateUi(Dialog_manage_links)
        QtCore.QMetaObject.connectSlotsByName(Dialog_manage_links)

    def retranslateUi(self, Dialog_manage_links):
        _translate = QtCore.QCoreApplication.translate
        Dialog_manage_links.setWindowTitle(_translate("Dialog_manage_links", "Manage file links"))
        self.label.setText(_translate("Dialog_manage_links", "Manage bad links to files"))
        self.label_1.setText(_translate("Dialog_manage_links", "Click on the file name to browse to the correct file location."))
        self.pushButton_search_folders.setToolTip(_translate("Dialog_manage_links", "<html><head/><body><p>Automatic search through folders for the file</p></body></html>"))
        self.pushButton_search_folders.setText(_translate("Dialog_manage_links", "Search folders"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_manage_links = QtWidgets.QDialog()
    ui = Ui_Dialog_manage_links()
    ui.setupUi(Dialog_manage_links)
    Dialog_manage_links.show()
    sys.exit(app.exec())
