# Form implementation generated from reading ui file 'ui_dialog_report_code_frequencies.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_reportCodeFrequencies(object):
    def setupUi(self, Dialog_reportCodeFrequencies):
        Dialog_reportCodeFrequencies.setObjectName("Dialog_reportCodeFrequencies")
        Dialog_reportCodeFrequencies.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        Dialog_reportCodeFrequencies.resize(694, 543)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_reportCodeFrequencies)
        self.verticalLayout.setContentsMargins(6, -1, 6, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=Dialog_reportCodeFrequencies)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 75))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 75))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_selections = QtWidgets.QLabel(parent=self.groupBox)
        self.label_selections.setGeometry(QtCore.QRect(10, -1, 481, 22))
        self.label_selections.setMinimumSize(QtCore.QSize(0, 22))
        self.label_selections.setMaximumSize(QtCore.QSize(16777213, 22))
        self.label_selections.setWordWrap(True)
        self.label_selections.setObjectName("label_selections")
        self.pushButton_exporttext = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_exporttext.setGeometry(QtCore.QRect(290, 30, 32, 32))
        self.pushButton_exporttext.setMinimumSize(QtCore.QSize(32, 32))
        self.pushButton_exporttext.setMaximumSize(QtCore.QSize(32, 32))
        self.pushButton_exporttext.setText("")
        self.pushButton_exporttext.setObjectName("pushButton_exporttext")
        self.pushButton_export_excel = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_export_excel.setGeometry(QtCore.QRect(330, 30, 32, 32))
        self.pushButton_export_excel.setMinimumSize(QtCore.QSize(32, 32))
        self.pushButton_export_excel.setMaximumSize(QtCore.QSize(32, 32))
        self.pushButton_export_excel.setText("")
        self.pushButton_export_excel.setObjectName("pushButton_export_excel")
        self.pushButton_select_files = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_select_files.setGeometry(QtCore.QRect(10, 30, 271, 32))
        self.pushButton_select_files.setObjectName("pushButton_select_files")
        self.radioButton = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(380, 24, 251, 23))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(380, 52, 251, 23))
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=Dialog_reportCodeFrequencies)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setContentsMargins(6, 6, 6, 6)
        self.gridLayout.setObjectName("gridLayout")
        self.treeWidget = QtWidgets.QTreeWidget(parent=self.groupBox_2)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.gridLayout.addWidget(self.treeWidget, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)

        self.retranslateUi(Dialog_reportCodeFrequencies)
        QtCore.QMetaObject.connectSlotsByName(Dialog_reportCodeFrequencies)
        Dialog_reportCodeFrequencies.setTabOrder(self.pushButton_select_files, self.pushButton_exporttext)
        Dialog_reportCodeFrequencies.setTabOrder(self.pushButton_exporttext, self.pushButton_export_excel)
        Dialog_reportCodeFrequencies.setTabOrder(self.pushButton_export_excel, self.radioButton)
        Dialog_reportCodeFrequencies.setTabOrder(self.radioButton, self.radioButton_2)
        Dialog_reportCodeFrequencies.setTabOrder(self.radioButton_2, self.treeWidget)

    def retranslateUi(self, Dialog_reportCodeFrequencies):
        _translate = QtCore.QCoreApplication.translate
        Dialog_reportCodeFrequencies.setWindowTitle(_translate("Dialog_reportCodeFrequencies", "Code frequencies"))
        self.label_selections.setText(_translate("Dialog_reportCodeFrequencies", "Code and category frequencies: overall and by coder"))
        self.pushButton_exporttext.setToolTip(_translate("Dialog_reportCodeFrequencies", "<html><head/><body><p>Export text file</p></body></html>"))
        self.pushButton_export_excel.setToolTip(_translate("Dialog_reportCodeFrequencies", "<html><head/><body><p>Export Excel</p></body></html>"))
        self.pushButton_select_files.setToolTip(_translate("Dialog_reportCodeFrequencies", "<html><head/><body><p>Select files</p></body></html>"))
        self.pushButton_select_files.setText(_translate("Dialog_reportCodeFrequencies", "Select files"))
        self.radioButton.setText(_translate("Dialog_reportCodeFrequencies", "Alphabetic ascending"))
        self.radioButton_2.setText(_translate("Dialog_reportCodeFrequencies", "Totals descending"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_reportCodeFrequencies = QtWidgets.QDialog()
    ui = Ui_Dialog_reportCodeFrequencies()
    ui.setupUi(Dialog_reportCodeFrequencies)
    Dialog_reportCodeFrequencies.show()
    sys.exit(app.exec())
