# Form implementation generated from reading ui file 'ui_dialog_select_items.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_selectitems(object):
    def setupUi(self, Dialog_selectitems):
        Dialog_selectitems.setObjectName("Dialog_selectitems")
        Dialog_selectitems.resize(482, 367)
        self.gridLayout = QtWidgets.QGridLayout(Dialog_selectitems)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox = QtWidgets.QComboBox(Dialog_selectitems)
        self.comboBox.setEnabled(True)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 1, 0, 1, 1)
        self.listView = QtWidgets.QListView(Dialog_selectitems)
        self.listView.setObjectName("listView")
        self.gridLayout.addWidget(self.listView, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_selectitems)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 1)

        self.retranslateUi(Dialog_selectitems)
        self.buttonBox.accepted.connect(Dialog_selectitems.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog_selectitems.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_selectitems)

    def retranslateUi(self, Dialog_selectitems):
        _translate = QtCore.QCoreApplication.translate
        Dialog_selectitems.setWindowTitle(_translate("Dialog_selectitems", "Select Items"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_selectitems = QtWidgets.QDialog()
    ui = Ui_Dialog_selectitems()
    ui.setupUi(Dialog_selectitems)
    Dialog_selectitems.show()
    sys.exit(app.exec())
