# Form implementation generated from reading ui file 'ui_dialog_charts.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogCharts(object):
    def setupUi(self, DialogCharts):
        DialogCharts.setObjectName("DialogCharts")
        DialogCharts.resize(918, 364)
        self.gridLayout = QtWidgets.QGridLayout(DialogCharts)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_header = QtWidgets.QGroupBox(DialogCharts)
        self.groupBox_header.setMinimumSize(QtCore.QSize(0, 70))
        self.groupBox_header.setMaximumSize(QtCore.QSize(16777215, 70))
        self.groupBox_header.setTitle("")
        self.groupBox_header.setObjectName("groupBox_header")
        self.label_pie_chart = QtWidgets.QLabel(self.groupBox_header)
        self.label_pie_chart.setGeometry(QtCore.QRect(10, 9, 101, 20))
        self.label_pie_chart.setObjectName("label_pie_chart")
        self.comboBox_pie_charts = QtWidgets.QComboBox(self.groupBox_header)
        self.comboBox_pie_charts.setGeometry(QtCore.QRect(10, 40, 271, 25))
        self.comboBox_pie_charts.setObjectName("comboBox_pie_charts")
        self.label_bar_chart = QtWidgets.QLabel(self.groupBox_header)
        self.label_bar_chart.setGeometry(QtCore.QRect(300, 9, 101, 20))
        self.label_bar_chart.setObjectName("label_bar_chart")
        self.comboBox_bar_charts = QtWidgets.QComboBox(self.groupBox_header)
        self.comboBox_bar_charts.setGeometry(QtCore.QRect(300, 40, 271, 25))
        self.comboBox_bar_charts.setObjectName("comboBox_bar_charts")
        self.label_tree_chart = QtWidgets.QLabel(self.groupBox_header)
        self.label_tree_chart.setGeometry(QtCore.QRect(590, 9, 101, 20))
        self.label_tree_chart.setObjectName("label_tree_chart")
        self.comboBox_tree_charts = QtWidgets.QComboBox(self.groupBox_header)
        self.comboBox_tree_charts.setGeometry(QtCore.QRect(590, 40, 271, 25))
        self.comboBox_tree_charts.setObjectName("comboBox_tree_charts")
        self.gridLayout.addWidget(self.groupBox_header, 0, 0, 1, 1)

        self.retranslateUi(DialogCharts)
        QtCore.QMetaObject.connectSlotsByName(DialogCharts)

    def retranslateUi(self, DialogCharts):
        _translate = QtCore.QCoreApplication.translate
        DialogCharts.setWindowTitle(_translate("DialogCharts", "Charts"))
        self.label_pie_chart.setText(_translate("DialogCharts", "Pie charts:"))
        self.label_bar_chart.setText(_translate("DialogCharts", "Bar charts:"))
        self.label_tree_chart.setText(_translate("DialogCharts", "Bar charts:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogCharts = QtWidgets.QDialog()
    ui = Ui_DialogCharts()
    ui.setupUi(DialogCharts)
    DialogCharts.show()
    sys.exit(app.exec())
