# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_dialog_colour_selector.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_colour_selector(object):
    def setupUi(self, Dialog_colour_selector):
        Dialog_colour_selector.setObjectName("Dialog_colour_selector")
        Dialog_colour_selector.resize(562, 440)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog_colour_selector.sizePolicy().hasHeightForWidth())
        Dialog_colour_selector.setSizePolicy(sizePolicy)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_colour_selector)
        self.buttonBox.setGeometry(QtCore.QRect(350, 20, 81, 71))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_colour_old = QtWidgets.QLabel(Dialog_colour_selector)
        self.label_colour_old.setGeometry(QtCore.QRect(10, 30, 101, 31))
        self.label_colour_old.setObjectName("label_colour_old")
        self.tableWidget = QtWidgets.QTableWidget(Dialog_colour_selector)
        self.tableWidget.setGeometry(QtCore.QRect(10, 100, 521, 252))
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(10)
        self.tableWidget.setRowCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.label_colour_new = QtWidgets.QLabel(Dialog_colour_selector)
        self.label_colour_new.setGeometry(QtCore.QRect(150, 30, 101, 31))
        self.label_colour_new.setObjectName("label_colour_new")

        self.retranslateUi(Dialog_colour_selector)
        self.buttonBox.accepted.connect(Dialog_colour_selector.accept)
        self.buttonBox.rejected.connect(Dialog_colour_selector.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_colour_selector)

    def retranslateUi(self, Dialog_colour_selector):
        _translate = QtCore.QCoreApplication.translate
        Dialog_colour_selector.setWindowTitle(_translate("Dialog_colour_selector", "Colour selector"))
        self.label_colour_old.setText(_translate("Dialog_colour_selector", "old"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Dialog_colour_selector", "New Row"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Dialog_colour_selector", "New Row"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Dialog_colour_selector", "New Row"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Dialog_colour_selector", "New Row"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Dialog_colour_selector", "New Row"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Dialog_colour_selector", "New Row"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Dialog_colour_selector", "New Row"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("Dialog_colour_selector", "New Row"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog_colour_selector", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog_colour_selector", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog_colour_selector", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog_colour_selector", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog_colour_selector", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog_colour_selector", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog_colour_selector", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Dialog_colour_selector", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Dialog_colour_selector", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("Dialog_colour_selector", "New Column"))
        self.label_colour_new.setText(_translate("Dialog_colour_selector", "new"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_colour_selector = QtWidgets.QDialog()
    ui = Ui_Dialog_colour_selector()
    ui.setupUi(Dialog_colour_selector)
    Dialog_colour_selector.show()
    sys.exit(app.exec_())
