# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_dialog_code_text.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_code_text(object):
    def setupUi(self, Dialog_code_text):
        Dialog_code_text.setObjectName("Dialog_code_text")
        Dialog_code_text.resize(1110, 695)
        self.gridLayout = QtWidgets.QGridLayout(Dialog_code_text)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(Dialog_code_text)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 100))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 100))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.pushButton_view_file = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_view_file.setGeometry(QtCore.QRect(10, 0, 151, 32))
        self.pushButton_view_file.setObjectName("pushButton_view_file")
        self.pushButton_auto_code = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_auto_code.setGeometry(QtCore.QRect(170, 0, 181, 32))
        self.pushButton_auto_code.setObjectName("pushButton_auto_code")
        self.label_coder = QtWidgets.QLabel(self.groupBox)
        self.label_coder.setGeometry(QtCore.QRect(360, 6, 271, 28))
        self.label_coder.setObjectName("label_coder")
        self.label_file = QtWidgets.QLabel(self.groupBox)
        self.label_file.setGeometry(QtCore.QRect(640, 7, 458, 28))
        self.label_file.setWordWrap(True)
        self.label_file.setObjectName("label_file")
        self.label_coded = QtWidgets.QLabel(self.groupBox)
        self.label_coded.setGeometry(QtCore.QRect(680, 70, 361, 28))
        self.label_coded.setObjectName("label_coded")
        self.label_code = QtWidgets.QLabel(self.groupBox)
        self.label_code.setGeometry(QtCore.QRect(0, 67, 441, 31))
        self.label_code.setObjectName("label_code")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(15, 40, 201, 26))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.lineEdit_search = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_search.setGeometry(QtCore.QRect(225, 37, 281, 32))
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.label_search_frequency = QtWidgets.QLabel(self.groupBox)
        self.label_search_frequency.setGeometry(QtCore.QRect(800, 40, 151, 26))
        self.label_search_frequency.setText("")
        self.label_search_frequency.setObjectName("label_search_frequency")
        self.label_search_frequency_2 = QtWidgets.QLabel(self.groupBox)
        self.label_search_frequency_2.setGeometry(QtCore.QRect(790, 40, 151, 26))
        self.label_search_frequency_2.setText("")
        self.label_search_frequency_2.setObjectName("label_search_frequency_2")
        self.pushButton_search_results = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_search_results.setGeometry(QtCore.QRect(520, 37, 161, 32))
        self.pushButton_search_results.setObjectName("pushButton_search_results")
        self.checkBox_search_case = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_search_case.setGeometry(QtCore.QRect(450, 70, 88, 22))
        self.checkBox_search_case.setObjectName("checkBox_search_case")
        self.checkBox_search_all_files = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_search_all_files.setGeometry(QtCore.QRect(560, 70, 88, 22))
        self.checkBox_search_all_files.setObjectName("checkBox_search_all_files")
        self.checkBox_search_escaped = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_search_escaped.setEnabled(False)
        self.checkBox_search_escaped.setGeometry(QtCore.QRect(630, 70, 31, 22))
        self.checkBox_search_escaped.setObjectName("checkBox_search_escaped")
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.splitter = QtWidgets.QSplitter(Dialog_code_text)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.leftsplitter = QtWidgets.QSplitter(self.splitter)
        self.leftsplitter.setOrientation(QtCore.Qt.Vertical)
        self.leftsplitter.setObjectName("leftsplitter")
        self.treeWidget = QtWidgets.QTreeWidget(self.leftsplitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setMinimumSize(QtCore.QSize(200, 0))
        self.treeWidget.setBaseSize(QtCore.QSize(200, 0))
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.textEdit = QtWidgets.QTextEdit(self.splitter)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.splitter, 1, 0, 1, 1)

        self.retranslateUi(Dialog_code_text)
        QtCore.QMetaObject.connectSlotsByName(Dialog_code_text)

    def retranslateUi(self, Dialog_code_text):
        _translate = QtCore.QCoreApplication.translate
        Dialog_code_text.setWindowTitle(_translate("Dialog_code_text", "Code Text"))
        self.pushButton_view_file.setToolTip(_translate("Dialog_code_text", "Select a file to view"))
        self.pushButton_view_file.setText(_translate("Dialog_code_text", "View File"))
        self.pushButton_auto_code.setText(_translate("Dialog_code_text", "Auto code"))
        self.label_coder.setText(_translate("Dialog_code_text", "Coder:"))
        self.label_file.setText(_translate("Dialog_code_text", "File:"))
        self.label_coded.setText(_translate("Dialog_code_text", "Right click to mark and unmark selected text"))
        self.label_code.setText(_translate("Dialog_code_text", "Right click below to create new codes and categories"))
        self.label.setText(_translate("Dialog_code_text", "Search for text:"))
        self.lineEdit_search.setToolTip(_translate("Dialog_code_text", "Case sensitive search"))
        self.pushButton_search_results.setText(_translate("Dialog_code_text", "0 of 0"))
        self.checkBox_search_case.setToolTip(_translate("Dialog_code_text", "<html><head/><body><p>search case sensitive</p></body></html>"))
        self.checkBox_search_case.setText(_translate("Dialog_code_text", "Case"))
        self.checkBox_search_all_files.setToolTip(_translate("Dialog_code_text", "<html><head/><body><p>search all files</p></body></html>"))
        self.checkBox_search_all_files.setText(_translate("Dialog_code_text", "All"))
        self.checkBox_search_escaped.setToolTip(_translate("Dialog_code_text", "<html><head/><body><p>Search escaped (no special regex characters)</p></body></html>"))
        self.checkBox_search_escaped.setText(_translate("Dialog_code_text", "Escaped"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_code_text = QtWidgets.QDialog()
    ui = Ui_Dialog_code_text()
    ui.setupUi(Dialog_code_text)
    Dialog_code_text.show()
    sys.exit(app.exec_())
