# Form implementation generated from reading ui file 'ui_dialog_colour_selector.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_colour_selector(object):
    def setupUi(self, Dialog_colour_selector):
        Dialog_colour_selector.setObjectName("Dialog_colour_selector")
        Dialog_colour_selector.resize(650, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog_colour_selector.sizePolicy().hasHeightForWidth())
        Dialog_colour_selector.setSizePolicy(sizePolicy)
        Dialog_colour_selector.setMinimumSize(QtCore.QSize(650, 500))
        Dialog_colour_selector.setMaximumSize(QtCore.QSize(650, 500))
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_colour_selector)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Dialog_colour_selector)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 80))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 80))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_colour_old = QtWidgets.QLabel(self.groupBox)
        self.label_colour_old.setGeometry(QtCore.QRect(10, 10, 281, 31))
        self.label_colour_old.setText("")
        self.label_colour_old.setWordWrap(True)
        self.label_colour_old.setObjectName("label_colour_old")
        self.label_colour_new = QtWidgets.QLabel(self.groupBox)
        self.label_colour_new.setGeometry(QtCore.QRect(10, 50, 281, 31))
        self.label_colour_new.setText("")
        self.label_colour_new.setWordWrap(True)
        self.label_colour_new.setObjectName("label_colour_new")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.groupBox)
        self.buttonBox.setGeometry(QtCore.QRect(430, 10, 81, 71))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_used = QtWidgets.QLabel(self.groupBox)
        self.label_used.setGeometry(QtCore.QRect(310, 10, 101, 41))
        self.label_used.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_used.setWordWrap(True)
        self.label_used.setObjectName("label_used")
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog_colour_selector)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(440, 20, 161, 17))
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_2)
        self.tableWidget.setGeometry(QtCore.QRect(10, 20, 394, 265))
        self.tableWidget.setMinimumSize(QtCore.QSize(394, 265))
        self.tableWidget.setMaximumSize(QtCore.QSize(394, 265))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton.setGeometry(QtCore.QRect(440, 60, 181, 23))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_2.setGeometry(QtCore.QRect(440, 90, 181, 23))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_3.setGeometry(QtCore.QRect(440, 120, 181, 23))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_4.setGeometry(QtCore.QRect(440, 150, 181, 23))
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_5.setGeometry(QtCore.QRect(440, 180, 181, 23))
        self.radioButton_5.setObjectName("radioButton_5")
        self.verticalLayout.addWidget(self.groupBox_2)
        self.label_2 = QtWidgets.QLabel(Dialog_colour_selector)
        self.label_2.setMinimumSize(QtCore.QSize(0, 34))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 34))
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.comboBox = QtWidgets.QComboBox(Dialog_colour_selector)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout.addWidget(self.comboBox)

        self.retranslateUi(Dialog_colour_selector)
        self.buttonBox.accepted.connect(Dialog_colour_selector.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog_colour_selector.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_colour_selector)

    def retranslateUi(self, Dialog_colour_selector):
        _translate = QtCore.QCoreApplication.translate
        Dialog_colour_selector.setWindowTitle(_translate("Dialog_colour_selector", "Colour selector"))
        self.label_used.setText(_translate("Dialog_colour_selector", "* Used"))
        self.label.setToolTip(_translate("Dialog_colour_selector", "<html><head/><body><p>Show how colours are seen with common types of colour blindness.</p></body></html>"))
        self.label.setText(_translate("Dialog_colour_selector", "Colour vision"))
        self.radioButton.setText(_translate("Dialog_colour_selector", "Normal"))
        self.radioButton_2.setText(_translate("Dialog_colour_selector", "Red weak"))
        self.radioButton_3.setText(_translate("Dialog_colour_selector", "Red blind"))
        self.radioButton_4.setText(_translate("Dialog_colour_selector", "Green weak"))
        self.radioButton_5.setText(_translate("Dialog_colour_selector", "Green blind"))
        self.label_2.setText(_translate("Dialog_colour_selector", "Apply colour range to category"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_colour_selector = QtWidgets.QDialog()
    ui = Ui_Dialog_colour_selector()
    ui.setupUi(Dialog_colour_selector)
    Dialog_colour_selector.show()
    sys.exit(app.exec())
