# Form implementation generated from reading ui file 'ui_import_twitter.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Import_twitter(object):
    def setupUi(self, Dialog_Import_twitter):
        Dialog_Import_twitter.setObjectName("Dialog_Import_twitter")
        Dialog_Import_twitter.resize(946, 579)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog_Import_twitter.sizePolicy().hasHeightForWidth())
        Dialog_Import_twitter.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(Dialog_Import_twitter)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(Dialog_Import_twitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 120))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 120))
        self.groupBox.setObjectName("groupBox")
        self.label_information = QtWidgets.QLabel(self.groupBox)
        self.label_information.setGeometry(QtCore.QRect(10, 30, 901, 40))
        self.label_information.setWordWrap(True)
        self.label_information.setObjectName("label_information")
        self.pushButton_select_file = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_select_file.setGeometry(QtCore.QRect(10, 80, 211, 30))
        self.pushButton_select_file.setObjectName("pushButton_select_file")
        self.label_file = QtWidgets.QLabel(self.groupBox)
        self.label_file.setGeometry(QtCore.QRect(420, 80, 481, 30))
        self.label_file.setText("")
        self.label_file.setObjectName("label_file")
        self.gridLayout.addWidget(self.groupBox, 3, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(Dialog_Import_twitter)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 4, 0, 1, 1)

        self.retranslateUi(Dialog_Import_twitter)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Import_twitter)

    def retranslateUi(self, Dialog_Import_twitter):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Import_twitter.setWindowTitle(_translate("Dialog_Import_twitter", "Twitter data import"))
        self.groupBox.setTitle(_translate("Dialog_Import_twitter", "Import twitter data file"))
        self.label_information.setText(_translate("Dialog_Import_twitter", "Use the R statistics package to get the twitter data and create a csv file. Then import the csv file."))
        self.pushButton_select_file.setText(_translate("Dialog_Import_twitter", "Select file"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_Import_twitter = QtWidgets.QDialog()
    ui = Ui_Dialog_Import_twitter()
    ui.setupUi(Dialog_Import_twitter)
    Dialog_Import_twitter.show()
    sys.exit(app.exec())
