# Form implementation generated from reading ui file 'ui_reference_manager.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_reference_manager(object):
    def setupUi(self, Dialog_reference_manager):
        Dialog_reference_manager.setObjectName("Dialog_reference_manager")
        Dialog_reference_manager.resize(899, 491)
        self.gridLayout = QtWidgets.QGridLayout(Dialog_reference_manager)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(Dialog_reference_manager)
        self.label_2.setMinimumSize(QtCore.QSize(0, 30))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.splitter = QtWidgets.QSplitter(Dialog_reference_manager)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setObjectName("splitter")
        self.tableWidget_refs = QtWidgets.QTableWidget(self.splitter)
        self.tableWidget_refs.setObjectName("tableWidget_refs")
        self.tableWidget_refs.setColumnCount(0)
        self.tableWidget_refs.setRowCount(0)
        self.tableWidget_files = QtWidgets.QTableWidget(self.splitter)
        self.tableWidget_files.setObjectName("tableWidget_files")
        self.tableWidget_files.setColumnCount(0)
        self.tableWidget_files.setRowCount(0)
        self.gridLayout.addWidget(self.splitter, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Dialog_reference_manager)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 110))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 110))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.pushButton_view_file = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_view_file.setGeometry(QtCore.QRect(300, 10, 181, 25))
        self.pushButton_view_file.setObjectName("pushButton_view_file")
        self.pushButton_view_ref = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_view_ref.setGeometry(QtCore.QRect(10, 10, 281, 25))
        self.pushButton_view_ref.setObjectName("pushButton_view_ref")
        self.pushButton_remove_unused = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_remove_unused.setGeometry(QtCore.QRect(490, 10, 381, 25))
        self.pushButton_remove_unused.setObjectName("pushButton_remove_unused")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.groupBox)
        self.buttonBox.setGeometry(QtCore.QRect(690, 70, 181, 25))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.checkBox_hide_files = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_hide_files.setGeometry(QtCore.QRect(20, 40, 271, 23))
        self.checkBox_hide_files.setObjectName("checkBox_hide_files")
        self.checkBox_hide_refs = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_hide_refs.setGeometry(QtCore.QRect(20, 70, 331, 23))
        self.checkBox_hide_refs.setObjectName("checkBox_hide_refs")
        self.gridLayout.addWidget(self.groupBox, 4, 0, 1, 1)

        self.retranslateUi(Dialog_reference_manager)
        self.buttonBox.accepted.connect(Dialog_reference_manager.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog_reference_manager.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_reference_manager)

    def retranslateUi(self, Dialog_reference_manager):
        _translate = QtCore.QCoreApplication.translate
        Dialog_reference_manager.setWindowTitle(_translate("Dialog_reference_manager", "Reference manager"))
        self.label_2.setText(_translate("Dialog_reference_manager", "Assign selected reference to file."))
        self.pushButton_view_file.setText(_translate("Dialog_reference_manager", "View file"))
        self.pushButton_view_ref.setText(_translate("Dialog_reference_manager", "View reference details"))
        self.pushButton_remove_unused.setText(_translate("Dialog_reference_manager", "Remove unused references"))
        self.checkBox_hide_files.setText(_translate("Dialog_reference_manager", "Hide assigned files"))
        self.checkBox_hide_refs.setText(_translate("Dialog_reference_manager", "Hide assigned references"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_reference_manager = QtWidgets.QDialog()
    ui = Ui_Dialog_reference_manager()
    ui.setupUi(Dialog_reference_manager)
    Dialog_reference_manager.show()
    sys.exit(app.exec())
