# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_special_functions.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_special_functions(object):
    def setupUi(self, Dialog_special_functions):
        Dialog_special_functions.setObjectName("Dialog_special_functions")
        Dialog_special_functions.resize(769, 527)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_special_functions)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog_special_functions)
        self.label.setMinimumSize(QtCore.QSize(0, 25))
        self.label.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.groupBox__base_directory = QtWidgets.QGroupBox(Dialog_special_functions)
        self.groupBox__base_directory.setMinimumSize(QtCore.QSize(0, 125))
        self.groupBox__base_directory.setMaximumSize(QtCore.QSize(16777215, 125))
        self.groupBox__base_directory.setStyleSheet("QGroupBox{border: 1px solid #f89407;}")
        self.groupBox__base_directory.setObjectName("groupBox__base_directory")
        self.label_example_linked_info = QtWidgets.QLabel(self.groupBox__base_directory)
        self.label_example_linked_info.setGeometry(QtCore.QRect(3, 20, 271, 17))
        self.label_example_linked_info.setObjectName("label_example_linked_info")
        self.label_example_linked_file = QtWidgets.QLabel(self.groupBox__base_directory)
        self.label_example_linked_file.setGeometry(QtCore.QRect(3, 40, 721, 17))
        self.label_example_linked_file.setObjectName("label_example_linked_file")
        self.label_prefix_old = QtWidgets.QLabel(self.groupBox__base_directory)
        self.label_prefix_old.setGeometry(QtCore.QRect(3, 60, 130, 17))
        self.label_prefix_old.setObjectName("label_prefix_old")
        self.label_4 = QtWidgets.QLabel(self.groupBox__base_directory)
        self.label_4.setGeometry(QtCore.QRect(3, 90, 121, 17))
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox__base_directory)
        self.lineEdit.setGeometry(QtCore.QRect(150, 58, 421, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox__base_directory)
        self.lineEdit_2.setGeometry(QtCore.QRect(150, 88, 421, 25))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_change_prefix = QtWidgets.QPushButton(self.groupBox__base_directory)
        self.pushButton_change_prefix.setGeometry(QtCore.QRect(680, 80, 32, 32))
        self.pushButton_change_prefix.setText("")
        self.pushButton_change_prefix.setObjectName("pushButton_change_prefix")
        self.verticalLayout.addWidget(self.groupBox__base_directory)
        self.groupBox_update_text = QtWidgets.QGroupBox(Dialog_special_functions)
        self.groupBox_update_text.setMinimumSize(QtCore.QSize(0, 110))
        self.groupBox_update_text.setMaximumSize(QtCore.QSize(16777215, 110))
        self.groupBox_update_text.setStyleSheet("QGroupBox{border: 1px solid #f89407;}")
        self.groupBox_update_text.setObjectName("groupBox_update_text")
        self.pushButton_text_update = QtWidgets.QPushButton(self.groupBox_update_text)
        self.pushButton_text_update.setGeometry(QtCore.QRect(700, 70, 32, 32))
        self.pushButton_text_update.setText("")
        self.pushButton_text_update.setObjectName("pushButton_text_update")
        self.label_text_update_info = QtWidgets.QLabel(self.groupBox_update_text)
        self.label_text_update_info.setGeometry(QtCore.QRect(50, 30, 621, 30))
        self.label_text_update_info.setObjectName("label_text_update_info")
        self.pushButton_select_text_file = QtWidgets.QPushButton(self.groupBox_update_text)
        self.pushButton_select_text_file.setGeometry(QtCore.QRect(6, 30, 32, 32))
        self.pushButton_select_text_file.setText("")
        self.pushButton_select_text_file.setObjectName("pushButton_select_text_file")
        self.label_text_update_info_2 = QtWidgets.QLabel(self.groupBox_update_text)
        self.label_text_update_info_2.setGeometry(QtCore.QRect(54, 73, 621, 30))
        self.label_text_update_info_2.setObjectName("label_text_update_info_2")
        self.pushButton_select_replacement_text_file = QtWidgets.QPushButton(self.groupBox_update_text)
        self.pushButton_select_replacement_text_file.setGeometry(QtCore.QRect(7, 70, 32, 32))
        self.pushButton_select_replacement_text_file.setText("")
        self.pushButton_select_replacement_text_file.setObjectName("pushButton_select_replacement_text_file")
        self.verticalLayout.addWidget(self.groupBox_update_text)
        self.groupBox_merge = QtWidgets.QGroupBox(Dialog_special_functions)
        self.groupBox_merge.setMinimumSize(QtCore.QSize(0, 70))
        self.groupBox_merge.setMaximumSize(QtCore.QSize(16777215, 70))
        self.groupBox_merge.setStyleSheet("QGroupBox{border: 1px solid #f89407;}")
        self.groupBox_merge.setObjectName("groupBox_merge")
        self.pushButton_merge = QtWidgets.QPushButton(self.groupBox_merge)
        self.pushButton_merge.setGeometry(QtCore.QRect(710, 30, 32, 32))
        self.pushButton_merge.setText("")
        self.pushButton_merge.setObjectName("pushButton_merge")
        self.pushButton_select_project = QtWidgets.QPushButton(self.groupBox_merge)
        self.pushButton_select_project.setGeometry(QtCore.QRect(16, 30, 32, 32))
        self.pushButton_select_project.setText("")
        self.pushButton_select_project.setObjectName("pushButton_select_project")
        self.label_merge_info = QtWidgets.QLabel(self.groupBox_merge)
        self.label_merge_info.setGeometry(QtCore.QRect(60, 30, 621, 30))
        self.label_merge_info.setObjectName("label_merge_info")
        self.verticalLayout.addWidget(self.groupBox_merge)
        self.groupBox_text_positions = QtWidgets.QGroupBox(Dialog_special_functions)
        self.groupBox_text_positions.setMinimumSize(QtCore.QSize(0, 120))
        self.groupBox_text_positions.setMaximumSize(QtCore.QSize(16777215, 120))
        self.groupBox_text_positions.setStyleSheet("QGroupBox{border: 1px solid #f89407;}")
        self.groupBox_text_positions.setObjectName("groupBox_text_positions")
        self.label_3 = QtWidgets.QLabel(self.groupBox_text_positions)
        self.label_3.setGeometry(QtCore.QRect(120, 80, 611, 30))
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox_text_positions)
        self.label_2.setGeometry(QtCore.QRect(120, 30, 611, 30))
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.spinBox_text_ends = QtWidgets.QSpinBox(self.groupBox_text_positions)
        self.spinBox_text_ends.setGeometry(QtCore.QRect(3, 80, 61, 32))
        self.spinBox_text_ends.setMinimum(-100)
        self.spinBox_text_ends.setMaximum(100)
        self.spinBox_text_ends.setObjectName("spinBox_text_ends")
        self.spinBox_text_starts = QtWidgets.QSpinBox(self.groupBox_text_positions)
        self.spinBox_text_starts.setGeometry(QtCore.QRect(3, 30, 61, 32))
        self.spinBox_text_starts.setMinimum(-100)
        self.spinBox_text_starts.setMaximum(100)
        self.spinBox_text_starts.setObjectName("spinBox_text_starts")
        self.pushButton_text_ends = QtWidgets.QPushButton(self.groupBox_text_positions)
        self.pushButton_text_ends.setGeometry(QtCore.QRect(70, 80, 32, 32))
        self.pushButton_text_ends.setText("")
        self.pushButton_text_ends.setObjectName("pushButton_text_ends")
        self.pushButton_text_starts = QtWidgets.QPushButton(self.groupBox_text_positions)
        self.pushButton_text_starts.setGeometry(QtCore.QRect(70, 30, 32, 32))
        self.pushButton_text_starts.setText("")
        self.pushButton_text_starts.setObjectName("pushButton_text_starts")
        self.verticalLayout.addWidget(self.groupBox_text_positions)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_special_functions)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog_special_functions)
        self.buttonBox.accepted.connect(Dialog_special_functions.accept)
        self.buttonBox.rejected.connect(Dialog_special_functions.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_special_functions)

    def retranslateUi(self, Dialog_special_functions):
        _translate = QtCore.QCoreApplication.translate
        Dialog_special_functions.setWindowTitle(_translate("Dialog_special_functions", "Special Functions"))
        self.label.setText(_translate("Dialog_special_functions", "Special functions. Backup project before running these functions."))
        self.groupBox__base_directory.setTitle(_translate("Dialog_special_functions", "Change base directory for linked files"))
        self.label_example_linked_info.setText(_translate("Dialog_special_functions", "Example linked file"))
        self.label_example_linked_file.setText(_translate("Dialog_special_functions", "."))
        self.label_prefix_old.setText(_translate("Dialog_special_functions", "Prefix to change"))
        self.label_4.setText(_translate("Dialog_special_functions", "New prefix"))
        self.pushButton_change_prefix.setToolTip(_translate("Dialog_special_functions", "Run"))
        self.groupBox_update_text.setTitle(_translate("Dialog_special_functions", "Dynamic update text content"))
        self.pushButton_text_update.setToolTip(_translate("Dialog_special_functions", "Run"))
        self.label_text_update_info.setText(_translate("Dialog_special_functions", "Select text file to update"))
        self.pushButton_select_text_file.setToolTip(_translate("Dialog_special_functions", "Select text file to update"))
        self.label_text_update_info_2.setText(_translate("Dialog_special_functions", "Select replacement text file"))
        self.pushButton_select_replacement_text_file.setToolTip(_translate("Dialog_special_functions", "Select replacement text file"))
        self.groupBox_merge.setTitle(_translate("Dialog_special_functions", "Merge projects"))
        self.pushButton_merge.setToolTip(_translate("Dialog_special_functions", "Run"))
        self.pushButton_select_project.setToolTip(_translate("Dialog_special_functions", "Select project to merge"))
        self.label_merge_info.setText(_translate("Dialog_special_functions", "Select project to merge"))
        self.groupBox_text_positions.setTitle(_translate("Dialog_special_functions", "Change text positions"))
        self.label_3.setText(_translate("Dialog_special_functions", "Change text code end positions ALL codes ALL files for current owner."))
        self.label_2.setText(_translate("Dialog_special_functions", "Change text code start positions ALL codes ALL files for current owner."))
        self.spinBox_text_ends.setToolTip(_translate("Dialog_special_functions", "<html><head/><body><p>Number of characters to extend (positive numbers)</p><p>or reduce (negative numbers)</p></body></html>"))
        self.spinBox_text_starts.setToolTip(_translate("Dialog_special_functions", "<html><head/><body><p>Number of characters to extend (positive numbers)</p><p>or reduce (negative numbers)</p></body></html>"))
        self.pushButton_text_ends.setToolTip(_translate("Dialog_special_functions", "Run"))
        self.pushButton_text_starts.setToolTip(_translate("Dialog_special_functions", "Run"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_special_functions = QtWidgets.QDialog()
    ui = Ui_Dialog_special_functions()
    ui.setupUi(Dialog_special_functions)
    Dialog_special_functions.show()
    sys.exit(app.exec_())
