# Form implementation generated from reading ui file '/home/qwerty/Bureau/QualCoder-removehtml/src/GUI_UIs/ui_dialog_manage_references_import.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogImportReferences(object):
    def setupUi(self, DialogImportReferences):
        DialogImportReferences.setObjectName("DialogImportReferences")
        DialogImportReferences.resize(820, 520)
        DialogImportReferences.setSizeGripEnabled(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogImportReferences)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_info = QtWidgets.QLabel(parent=DialogImportReferences)
        self.label_info.setWordWrap(True)
        self.label_info.setObjectName("label_info")
        self.verticalLayout.addWidget(self.label_info)
        self.horizontalLayout_top = QtWidgets.QHBoxLayout()
        self.horizontalLayout_top.setObjectName("horizontalLayout_top")
        self.pushButton_select_all = QtWidgets.QPushButton(parent=DialogImportReferences)
        self.pushButton_select_all.setObjectName("pushButton_select_all")
        self.horizontalLayout_top.addWidget(self.pushButton_select_all)
        self.pushButton_select_none = QtWidgets.QPushButton(parent=DialogImportReferences)
        self.pushButton_select_none.setObjectName("pushButton_select_none")
        self.horizontalLayout_top.addWidget(self.pushButton_select_none)
        self.pushButton_select_new = QtWidgets.QPushButton(parent=DialogImportReferences)
        self.pushButton_select_new.setObjectName("pushButton_select_new")
        self.horizontalLayout_top.addWidget(self.pushButton_select_new)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_top.addItem(spacerItem)
        self.checkBox_import_attachments = QtWidgets.QCheckBox(parent=DialogImportReferences)
        self.checkBox_import_attachments.setChecked(True)
        self.checkBox_import_attachments.setObjectName("checkBox_import_attachments")
        self.horizontalLayout_top.addWidget(self.checkBox_import_attachments)
        self.verticalLayout.addLayout(self.horizontalLayout_top)
        self.tableWidget = QtWidgets.QTableWidget(parent=DialogImportReferences)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tableWidget)
        self.label_summary = QtWidgets.QLabel(parent=DialogImportReferences)
        self.label_summary.setText("")
        self.label_summary.setObjectName("label_summary")
        self.verticalLayout.addWidget(self.label_summary)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=DialogImportReferences)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(DialogImportReferences)
        self.buttonBox.accepted.connect(DialogImportReferences.accept) # type: ignore
        self.buttonBox.rejected.connect(DialogImportReferences.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogImportReferences)

    def retranslateUi(self, DialogImportReferences):
        _translate = QtCore.QCoreApplication.translate
        DialogImportReferences.setWindowTitle(_translate("DialogImportReferences", "Import references"))
        self.label_info.setText(_translate("DialogImportReferences", "Select the references to import. Items already in the project (duplicates) are unchecked by default."))
        self.pushButton_select_all.setText(_translate("DialogImportReferences", "Select all"))
        self.pushButton_select_none.setText(_translate("DialogImportReferences", "Deselect all"))
        self.pushButton_select_new.setText(_translate("DialogImportReferences", "Only New"))
        self.checkBox_import_attachments.setText(_translate("DialogImportReferences", "Import attachments (PDF/EPUB)"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("DialogImportReferences", "Import"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("DialogImportReferences", "Reference"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("DialogImportReferences", "Status"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("DialogImportReferences", "Attachment"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("DialogImportReferences", "Attachment status"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogImportReferences = QtWidgets.QDialog()
    ui = Ui_DialogImportReferences()
    ui.setupUi(DialogImportReferences)
    DialogImportReferences.show()
    sys.exit(app.exec())
