# Form implementation generated from reading ui file '/home/qwerty/Bureau/QualCoder-removehtml/src/GUI_UIs/ui_dialog_memo.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_memo(object):
    def setupUi(self, Dialog_memo):
        Dialog_memo.setObjectName("Dialog_memo")
        Dialog_memo.resize(541, 396)
        self.gridLayout = QtWidgets.QGridLayout(Dialog_memo)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_toolbar = QtWidgets.QGroupBox(parent=Dialog_memo)
        self.groupBox_toolbar.setMinimumSize(QtCore.QSize(0, 32))
        self.groupBox_toolbar.setMaximumSize(QtCore.QSize(16777215, 32))
        self.groupBox_toolbar.setTitle("")
        self.groupBox_toolbar.setObjectName("groupBox_toolbar")
        self.pushButton_insert_datetime = QtWidgets.QPushButton(parent=self.groupBox_toolbar)
        self.pushButton_insert_datetime.setGeometry(QtCore.QRect(10, 2, 28, 28))
        self.pushButton_insert_datetime.setText("")
        self.pushButton_insert_datetime.setObjectName("pushButton_insert_datetime")
        self.pushButton_insert_coded_segment = QtWidgets.QPushButton(parent=self.groupBox_toolbar)
        self.pushButton_insert_coded_segment.setGeometry(QtCore.QRect(40, 2, 28, 28))
        self.pushButton_insert_coded_segment.setText("")
        self.pushButton_insert_coded_segment.setObjectName("pushButton_insert_coded_segment")
        self.pushButton_insert_reference = QtWidgets.QPushButton(parent=self.groupBox_toolbar)
        self.pushButton_insert_reference.setGeometry(QtCore.QRect(70, 2, 28, 28))
        self.pushButton_insert_reference.setText("")
        self.pushButton_insert_reference.setObjectName("pushButton_insert_reference")
        self.pushButton_export_odt = QtWidgets.QPushButton(parent=self.groupBox_toolbar)
        self.pushButton_export_odt.setGeometry(QtCore.QRect(100, 2, 28, 28))
        self.pushButton_export_odt.setText("")
        self.pushButton_export_odt.setObjectName("pushButton_export_odt")
        self.gridLayout.addWidget(self.groupBox_toolbar, 0, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(parent=Dialog_memo)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(parent=Dialog_memo)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 30))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 30))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=self.groupBox)
        self.buttonBox.setGeometry(QtCore.QRect(170, 0, 221, 25))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.pushButton_clear = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_clear.setGeometry(QtCore.QRect(10, 0, 89, 25))
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.gridLayout.addWidget(self.groupBox, 2, 0, 1, 1)

        self.retranslateUi(Dialog_memo)
        self.buttonBox.accepted.connect(Dialog_memo.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog_memo.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_memo)

    def retranslateUi(self, Dialog_memo):
        _translate = QtCore.QCoreApplication.translate
        Dialog_memo.setWindowTitle(_translate("Dialog_memo", "Memo"))
        self.pushButton_insert_datetime.setToolTip(_translate("Dialog_memo", "Insert current date and time at the cursor position"))
        self.pushButton_insert_coded_segment.setToolTip(_translate("Dialog_memo", "Insert coded segments linked to this item"))
        self.pushButton_insert_reference.setToolTip(_translate("Dialog_memo", "Insert a bibliographic reference linked to this item"))
        self.pushButton_export_odt.setToolTip(_translate("Dialog_memo", "Export memo as ODT file"))
        self.pushButton_clear.setText(_translate("Dialog_memo", "Clear"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_memo = QtWidgets.QDialog()
    ui = Ui_Dialog_memo()
    ui.setupUi(Dialog_memo)
    Dialog_memo.show()
    sys.exit(app.exec())
