# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_dialog_code_text.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_code_text(object):
    def setupUi(self, Dialog_code_text):
        Dialog_code_text.setObjectName("Dialog_code_text")
        Dialog_code_text.resize(1110, 695)
        self.gridLayout = QtWidgets.QGridLayout(Dialog_code_text)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(Dialog_code_text)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 120))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 120))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.pushButton_view_file = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_view_file.setGeometry(QtCore.QRect(10, 0, 151, 32))
        self.pushButton_view_file.setObjectName("pushButton_view_file")
        self.pushButton_auto_code = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_auto_code.setGeometry(QtCore.QRect(360, 40, 191, 32))
        self.pushButton_auto_code.setObjectName("pushButton_auto_code")
        self.label_coder = QtWidgets.QLabel(self.groupBox)
        self.label_coder.setGeometry(QtCore.QRect(10, 40, 341, 28))
        self.label_coder.setObjectName("label_coder")
        self.label_code = QtWidgets.QLabel(self.groupBox)
        self.label_code.setGeometry(QtCore.QRect(10, 73, 401, 41))
        self.label_code.setWordWrap(True)
        self.label_code.setObjectName("label_code")
        self.label_search = QtWidgets.QLabel(self.groupBox)
        self.label_search.setGeometry(QtCore.QRect(170, 0, 181, 26))
        self.label_search.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_search.setWordWrap(True)
        self.label_search.setObjectName("label_search")
        self.lineEdit_search = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_search.setGeometry(QtCore.QRect(360, 0, 191, 32))
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.checkBox_search_case = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_search_case.setGeometry(QtCore.QRect(720, 0, 171, 22))
        self.checkBox_search_case.setObjectName("checkBox_search_case")
        self.checkBox_search_all_files = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_search_all_files.setGeometry(QtCore.QRect(900, 0, 141, 22))
        self.checkBox_search_all_files.setObjectName("checkBox_search_all_files")
        self.label_search_totals = QtWidgets.QLabel(self.groupBox)
        self.label_search_totals.setGeometry(QtCore.QRect(588, 0, 81, 22))
        self.label_search_totals.setAlignment(QtCore.Qt.AlignCenter)
        self.label_search_totals.setObjectName("label_search_totals")
        self.label_codes_clicked_in_text = QtWidgets.QLabel(self.groupBox)
        self.label_codes_clicked_in_text.setGeometry(QtCore.QRect(640, 46, 431, 22))
        self.label_codes_clicked_in_text.setObjectName("label_codes_clicked_in_text")
        self.label_codes_count = QtWidgets.QLabel(self.groupBox)
        self.label_codes_count.setGeometry(QtCore.QRect(590, 46, 41, 22))
        self.label_codes_count.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_codes_count.setObjectName("label_codes_count")
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setGeometry(QtCore.QRect(560, 30, 531, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.groupBox)
        self.line_2.setGeometry(QtCore.QRect(554, 40, 16, 91))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.comboBox_codes_in_text = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_codes_in_text.setGeometry(QtCore.QRect(580, 80, 491, 31))
        self.comboBox_codes_in_text.setObjectName("comboBox_codes_in_text")
        self.pushButton_previous = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_previous.setGeometry(QtCore.QRect(560, 0, 21, 25))
        self.pushButton_previous.setObjectName("pushButton_previous")
        self.pushButton_next = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_next.setGeometry(QtCore.QRect(680, 0, 21, 25))
        self.pushButton_next.setObjectName("pushButton_next")
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.splitter = QtWidgets.QSplitter(Dialog_code_text)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.leftsplitter = QtWidgets.QSplitter(self.splitter)
        self.leftsplitter.setOrientation(QtCore.Qt.Vertical)
        self.leftsplitter.setObjectName("leftsplitter")
        self.treeWidget = QtWidgets.QTreeWidget(self.leftsplitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setMinimumSize(QtCore.QSize(200, 0))
        self.treeWidget.setBaseSize(QtCore.QSize(200, 0))
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.textEdit = QtWidgets.QTextEdit(self.splitter)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.splitter, 1, 0, 1, 1)

        self.retranslateUi(Dialog_code_text)
        QtCore.QMetaObject.connectSlotsByName(Dialog_code_text)
        Dialog_code_text.setTabOrder(self.pushButton_view_file, self.lineEdit_search)
        Dialog_code_text.setTabOrder(self.lineEdit_search, self.pushButton_previous)
        Dialog_code_text.setTabOrder(self.pushButton_previous, self.pushButton_next)
        Dialog_code_text.setTabOrder(self.pushButton_next, self.checkBox_search_case)
        Dialog_code_text.setTabOrder(self.checkBox_search_case, self.checkBox_search_all_files)
        Dialog_code_text.setTabOrder(self.checkBox_search_all_files, self.pushButton_auto_code)
        Dialog_code_text.setTabOrder(self.pushButton_auto_code, self.comboBox_codes_in_text)
        Dialog_code_text.setTabOrder(self.comboBox_codes_in_text, self.treeWidget)
        Dialog_code_text.setTabOrder(self.treeWidget, self.textEdit)

    def retranslateUi(self, Dialog_code_text):
        _translate = QtCore.QCoreApplication.translate
        Dialog_code_text.setWindowTitle(_translate("Dialog_code_text", "Code Text"))
        self.pushButton_view_file.setToolTip(_translate("Dialog_code_text", "Select a file to view"))
        self.pushButton_view_file.setText(_translate("Dialog_code_text", "View File"))
        self.pushButton_auto_code.setText(_translate("Dialog_code_text", "Auto code"))
        self.label_coder.setText(_translate("Dialog_code_text", "Coder:"))
        self.label_code.setText(_translate("Dialog_code_text", "Right click below to create new codes and categories"))
        self.label_search.setText(_translate("Dialog_code_text", "Search for text:"))
        self.lineEdit_search.setToolTip(_translate("Dialog_code_text", "<html><head/><body><p>Search for text.</p><p>check <span style=\" font-weight:600;\">Case sensitive</span> for case sensitive search</p><p>check <span style=\" font-weight:600;\">All files</span> for searching all files search</p></body></html>"))
        self.checkBox_search_case.setToolTip(_translate("Dialog_code_text", "<html><head/><body><p>search case sensitive</p></body></html>"))
        self.checkBox_search_case.setText(_translate("Dialog_code_text", "Case sensitive"))
        self.checkBox_search_all_files.setToolTip(_translate("Dialog_code_text", "<html><head/><body><p>search all files</p></body></html>"))
        self.checkBox_search_all_files.setText(_translate("Dialog_code_text", "All files"))
        self.label_search_totals.setText(_translate("Dialog_code_text", "0 / 0"))
        self.label_codes_clicked_in_text.setText(_translate("Dialog_code_text", "Overlapping codes at clicked position"))
        self.label_codes_count.setText(_translate("Dialog_code_text", "0"))
        self.pushButton_previous.setText(_translate("Dialog_code_text", "<"))
        self.pushButton_next.setText(_translate("Dialog_code_text", ">"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_code_text = QtWidgets.QDialog()
    ui = Ui_Dialog_code_text()
    ui.setupUi(Dialog_code_text)
    Dialog_code_text.show()
    sys.exit(app.exec_())
