name: Execute rebuild_lang.py

on:
  workflow_dispatch:
    inputs:
      script_args:
        description: "Arguments pour rebuild_lang.py (ex: --update --lang fr)"
        required: false
        default: "--update"

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: pip install lxml polib PyQt5

      - name: Install gettext tools (xgettext, msgmerge)
        run: sudo apt-get update && sudo apt-get install -y gettext

      - name: Install Qt tools (pylupdate5, lrelease)
        run: sudo apt-get install -y qttools5-dev-tools

      - name: Execute rebuild_lang.py
        run: python rebuild_lang.py ${{ github.event.inputs.script_args }}
