# Form implementation generated from reading ui file 'ui_dialog_colour_selector.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_colour_selector(object):
    def setupUi(self, Dialog_colour_selector):
        Dialog_colour_selector.setObjectName("Dialog_colour_selector")
        Dialog_colour_selector.resize(650, 450)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog_colour_selector.sizePolicy().hasHeightForWidth())
        Dialog_colour_selector.setSizePolicy(sizePolicy)
        Dialog_colour_selector.setMinimumSize(QtCore.QSize(650, 450))
        Dialog_colour_selector.setMaximumSize(QtCore.QSize(650, 450))
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_colour_selector)
        self.verticalLayout.setContentsMargins(3, 9, 3, 9)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Dialog_colour_selector)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 80))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 80))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_colour_old = QtWidgets.QLabel(self.groupBox)
        self.label_colour_old.setGeometry(QtCore.QRect(10, 10, 281, 31))
        self.label_colour_old.setText("")
        self.label_colour_old.setWordWrap(True)
        self.label_colour_old.setObjectName("label_colour_old")
        self.label_colour_new = QtWidgets.QLabel(self.groupBox)
        self.label_colour_new.setGeometry(QtCore.QRect(10, 50, 281, 31))
        self.label_colour_new.setText("")
        self.label_colour_new.setWordWrap(True)
        self.label_colour_new.setObjectName("label_colour_new")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.groupBox)
        self.buttonBox.setGeometry(QtCore.QRect(430, 10, 81, 71))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_used = QtWidgets.QLabel(self.groupBox)
        self.label_used.setGeometry(QtCore.QRect(310, 10, 101, 41))
        self.label_used.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_used.setWordWrap(True)
        self.label_used.setObjectName("label_used")
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog_colour_selector)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_2)
        self.tableWidget.setMinimumSize(QtCore.QSize(420, 290))
        self.tableWidget.setMaximumSize(QtCore.QSize(420, 290))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.groupBox_color_vision = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_color_vision.setMinimumSize(QtCore.QSize(180, 0))
        self.groupBox_color_vision.setMaximumSize(QtCore.QSize(2000, 16777215))
        self.groupBox_color_vision.setObjectName("groupBox_color_vision")
        self.radioButton_normal = QtWidgets.QRadioButton(self.groupBox_color_vision)
        self.radioButton_normal.setGeometry(QtCore.QRect(10, 30, 181, 23))
        self.radioButton_normal.setChecked(True)
        self.radioButton_normal.setObjectName("radioButton_normal")
        self.radioButton_red_weak = QtWidgets.QRadioButton(self.groupBox_color_vision)
        self.radioButton_red_weak.setGeometry(QtCore.QRect(10, 60, 181, 23))
        self.radioButton_red_weak.setObjectName("radioButton_red_weak")
        self.radioButton_red_blind = QtWidgets.QRadioButton(self.groupBox_color_vision)
        self.radioButton_red_blind.setGeometry(QtCore.QRect(10, 90, 181, 23))
        self.radioButton_red_blind.setObjectName("radioButton_red_blind")
        self.radioButton_green_weak = QtWidgets.QRadioButton(self.groupBox_color_vision)
        self.radioButton_green_weak.setGeometry(QtCore.QRect(10, 120, 181, 23))
        self.radioButton_green_weak.setObjectName("radioButton_green_weak")
        self.radioButton_green_blind = QtWidgets.QRadioButton(self.groupBox_color_vision)
        self.radioButton_green_blind.setGeometry(QtCore.QRect(10, 150, 181, 23))
        self.radioButton_green_blind.setObjectName("radioButton_green_blind")
        self.gridLayout.addWidget(self.groupBox_color_vision, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)

        self.retranslateUi(Dialog_colour_selector)
        self.buttonBox.accepted.connect(Dialog_colour_selector.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog_colour_selector.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_colour_selector)

    def retranslateUi(self, Dialog_colour_selector):
        _translate = QtCore.QCoreApplication.translate
        Dialog_colour_selector.setWindowTitle(_translate("Dialog_colour_selector", "Colour selector"))
        self.label_used.setText(_translate("Dialog_colour_selector", "* Used"))
        self.groupBox_color_vision.setTitle(_translate("Dialog_colour_selector", "Color vision"))
        self.radioButton_normal.setText(_translate("Dialog_colour_selector", "Normal"))
        self.radioButton_red_weak.setText(_translate("Dialog_colour_selector", "Red weak"))
        self.radioButton_red_blind.setText(_translate("Dialog_colour_selector", "Red blind"))
        self.radioButton_green_weak.setText(_translate("Dialog_colour_selector", "Green weak"))
        self.radioButton_green_blind.setText(_translate("Dialog_colour_selector", "Green blind"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_colour_selector = QtWidgets.QDialog()
    ui = Ui_Dialog_colour_selector()
    ui.setupUi(Dialog_colour_selector)
    Dialog_colour_selector.show()
    sys.exit(app.exec())
