# Form implementation generated from reading ui file 'ui_dialog_select_quote.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_select_quote(object):
    def setupUi(self, Dialog_select_quote):
        Dialog_select_quote.setObjectName("Dialog_select_quote")
        Dialog_select_quote.resize(860, 500)
        self.gridLayout = QtWidgets.QGridLayout(Dialog_select_quote)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_scope = QtWidgets.QLabel(parent=Dialog_select_quote)
        self.label_scope.setObjectName("label_scope")
        self.horizontalLayout.addWidget(self.label_scope)
        self.comboBox_type = QtWidgets.QComboBox(parent=Dialog_select_quote)
        self.comboBox_type.setObjectName("comboBox_type")
        self.horizontalLayout.addWidget(self.comboBox_type)
        self.lineEdit_filter = QtWidgets.QLineEdit(parent=Dialog_select_quote)
        self.lineEdit_filter.setObjectName("lineEdit_filter")
        self.horizontalLayout.addWidget(self.lineEdit_filter)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(parent=Dialog_select_quote)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.ExtendedSelection)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 1, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog_select_quote)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 1)

        self.retranslateUi(Dialog_select_quote)
        self.buttonBox.accepted.connect(Dialog_select_quote.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog_select_quote.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_select_quote)

    def retranslateUi(self, Dialog_select_quote):
        _translate = QtCore.QCoreApplication.translate
        Dialog_select_quote.setWindowTitle(_translate("Dialog_select_quote", "Select quotes"))
        self.label_scope.setText(_translate("Dialog_select_quote", "Coded segments"))
        self.comboBox_type.setToolTip(_translate("Dialog_select_quote", "Filter by segment type"))
        self.lineEdit_filter.setToolTip(_translate("Dialog_select_quote", "Filter rows by any text"))
        self.lineEdit_filter.setPlaceholderText(_translate("Dialog_select_quote", "Filter"))
