# Form implementation generated from reading ui file 'ui_dialog_report_file_summary.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_file_summary(object):
    def setupUi(self, Dialog_file_summary):
        Dialog_file_summary.setObjectName("Dialog_file_summary")
        Dialog_file_summary.resize(880, 670)
        self.gridLayout = QtWidgets.QGridLayout(Dialog_file_summary)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=Dialog_file_summary)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_2.setVerticalSpacing(2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter = QtWidgets.QSplitter(parent=self.groupBox_2)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setObjectName("splitter")
        self.listWidget = QtWidgets.QListWidget(parent=self.splitter)
        self.listWidget.setObjectName("listWidget")
        self.textEdit = QtWidgets.QTextEdit(parent=self.splitter)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_2.addWidget(self.splitter, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(parent=self.groupBox_2)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 36))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 36))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_search_results = QtWidgets.QLabel(parent=self.groupBox)
        self.label_search_results.setGeometry(QtCore.QRect(290, 0, 111, 28))
        self.label_search_results.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_search_results.setWordWrap(True)
        self.label_search_results.setObjectName("label_search_results")
        self.lineEdit_search_results = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit_search_results.setGeometry(QtCore.QRect(410, 0, 151, 28))
        self.lineEdit_search_results.setObjectName("lineEdit_search_results")
        self.pushButton_search_next = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_search_next.setGeometry(QtCore.QRect(570, 0, 28, 28))
        self.pushButton_search_next.setText("")
        self.pushButton_search_next.setObjectName("pushButton_search_next")
        self.label_files = QtWidgets.QLabel(parent=self.groupBox)
        self.label_files.setGeometry(QtCore.QRect(0, 0, 281, 28))
        self.label_files.setMinimumSize(QtCore.QSize(0, 28))
        self.label_files.setMaximumSize(QtCore.QSize(16777215, 28))
        self.label_files.setObjectName("label_files")
        self.comboBox_stopwords = QtWidgets.QComboBox(parent=self.groupBox)
        self.comboBox_stopwords.setGeometry(QtCore.QRect(620, 0, 181, 28))
        self.comboBox_stopwords.setObjectName("comboBox_stopwords")
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 1, 1, 1, 1)

        self.retranslateUi(Dialog_file_summary)
        QtCore.QMetaObject.connectSlotsByName(Dialog_file_summary)
        Dialog_file_summary.setTabOrder(self.listWidget, self.textEdit)

    def retranslateUi(self, Dialog_file_summary):
        _translate = QtCore.QCoreApplication.translate
        Dialog_file_summary.setWindowTitle(_translate("Dialog_file_summary", "File summary"))
        self.label_search_results.setText(_translate("Dialog_file_summary", "Search:"))
        self.lineEdit_search_results.setToolTip(_translate("Dialog_file_summary", "Search results for text"))
        self.pushButton_search_next.setToolTip(_translate("Dialog_file_summary", "Search for next occurence in results"))
        self.label_files.setText(_translate("Dialog_file_summary", "File summary report"))
        self.comboBox_stopwords.setToolTip(_translate("Dialog_file_summary", "Select stopwords list by language"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_file_summary = QtWidgets.QDialog()
    ui = Ui_Dialog_file_summary()
    ui.setupUi(Dialog_file_summary)
    Dialog_file_summary.show()
    sys.exit(app.exec())
