# Form implementation generated from reading ui file 'ui_dialog_manage_files.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_manage_files(object):
    def setupUi(self, Dialog_manage_files):
        Dialog_manage_files.setObjectName("Dialog_manage_files")
        Dialog_manage_files.resize(805, 538)
        self.gridLayout = QtWidgets.QGridLayout(Dialog_manage_files)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=Dialog_manage_files)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 38))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 38))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.pushButton_view = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_view.setGeometry(QtCore.QRect(30, 3, 30, 30))
        self.pushButton_view.setText("")
        self.pushButton_view.setObjectName("pushButton_view")
        self.pushButton_create = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_create.setGeometry(QtCore.QRect(120, 3, 30, 30))
        self.pushButton_create.setText("")
        self.pushButton_create.setObjectName("pushButton_create")
        self.pushButton_export = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_export.setGeometry(QtCore.QRect(430, 3, 30, 30))
        self.pushButton_export.setText("")
        self.pushButton_export.setObjectName("pushButton_export")
        self.pushButton_delete = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_delete.setGeometry(QtCore.QRect(640, 3, 30, 30))
        self.pushButton_delete.setText("")
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.pushButton_import = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_import.setGeometry(QtCore.QRect(60, 3, 30, 30))
        self.pushButton_import.setText("")
        self.pushButton_import.setObjectName("pushButton_import")
        self.pushButton_add_attribute = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_add_attribute.setGeometry(QtCore.QRect(210, 3, 30, 30))
        self.pushButton_add_attribute.setText("")
        self.pushButton_add_attribute.setObjectName("pushButton_add_attribute")
        self.pushButton_link = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_link.setGeometry(QtCore.QRect(90, 3, 30, 30))
        self.pushButton_link.setText("")
        self.pushButton_link.setObjectName("pushButton_link")
        self.pushButton_import_from_linked = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_import_from_linked.setGeometry(QtCore.QRect(150, 3, 30, 30))
        self.pushButton_import_from_linked.setText("")
        self.pushButton_import_from_linked.setObjectName("pushButton_import_from_linked")
        self.pushButton_export_to_linked = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_export_to_linked.setGeometry(QtCore.QRect(180, 3, 30, 30))
        self.pushButton_export_to_linked.setText("")
        self.pushButton_export_to_linked.setObjectName("pushButton_export_to_linked")
        self.pushButton_export_attributes = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_export_attributes.setGeometry(QtCore.QRect(390, 3, 30, 30))
        self.pushButton_export_attributes.setText("")
        self.pushButton_export_attributes.setObjectName("pushButton_export_attributes")
        self.pushButton_help = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_help.setGeometry(QtCore.QRect(710, 3, 30, 30))
        self.pushButton_help.setText("")
        self.pushButton_help.setObjectName("pushButton_help")
        self.label_fcount = QtWidgets.QLabel(parent=self.groupBox)
        self.label_fcount.setGeometry(QtCore.QRect(260, 6, 121, 26))
        self.label_fcount.setObjectName("label_fcount")
        self.pushButton_undo = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_undo.setEnabled(False)
        self.pushButton_undo.setGeometry(QtCore.QRect(610, 3, 30, 30))
        self.pushButton_undo.setText("")
        self.pushButton_undo.setObjectName("pushButton_undo")
        self.pushButton_bulk_rename = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_bulk_rename.setGeometry(QtCore.QRect(580, 3, 30, 30))
        self.pushButton_bulk_rename.setText("")
        self.pushButton_bulk_rename.setObjectName("pushButton_bulk_rename")
        self.pushButton_display_save = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_display_save.setGeometry(QtCore.QRect(500, 3, 30, 30))
        self.pushButton_display_save.setText("")
        self.pushButton_display_save.setObjectName("pushButton_display_save")
        self.pushButton_display_load = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_display_load.setGeometry(QtCore.QRect(470, 3, 30, 30))
        self.pushButton_display_load.setText("")
        self.pushButton_display_load.setObjectName("pushButton_display_load")
        self.pushButton_display_delete = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_display_delete.setGeometry(QtCore.QRect(530, 3, 30, 30))
        self.pushButton_display_delete.setText("")
        self.pushButton_display_delete.setObjectName("pushButton_display_delete")
        self.pushButton_pseudonyms = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_pseudonyms.setGeometry(QtCore.QRect(0, 3, 30, 30))
        self.pushButton_pseudonyms.setText("")
        self.pushButton_pseudonyms.setObjectName("pushButton_pseudonyms")
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(parent=Dialog_manage_files)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 3, 0, 1, 1)
        self.label_file = QtWidgets.QLabel(parent=Dialog_manage_files)
        self.label_file.setObjectName("label_file")
        self.gridLayout.addWidget(self.label_file, 2, 0, 1, 1)

        self.retranslateUi(Dialog_manage_files)
        QtCore.QMetaObject.connectSlotsByName(Dialog_manage_files)
        Dialog_manage_files.setTabOrder(self.pushButton_view, self.pushButton_import)
        Dialog_manage_files.setTabOrder(self.pushButton_import, self.pushButton_link)
        Dialog_manage_files.setTabOrder(self.pushButton_link, self.pushButton_create)
        Dialog_manage_files.setTabOrder(self.pushButton_create, self.pushButton_import_from_linked)
        Dialog_manage_files.setTabOrder(self.pushButton_import_from_linked, self.pushButton_export_to_linked)
        Dialog_manage_files.setTabOrder(self.pushButton_export_to_linked, self.pushButton_add_attribute)
        Dialog_manage_files.setTabOrder(self.pushButton_add_attribute, self.pushButton_export_attributes)
        Dialog_manage_files.setTabOrder(self.pushButton_export_attributes, self.pushButton_export)
        Dialog_manage_files.setTabOrder(self.pushButton_export, self.pushButton_help)
        Dialog_manage_files.setTabOrder(self.pushButton_help, self.pushButton_undo)
        Dialog_manage_files.setTabOrder(self.pushButton_undo, self.pushButton_delete)
        Dialog_manage_files.setTabOrder(self.pushButton_delete, self.tableWidget)

    def retranslateUi(self, Dialog_manage_files):
        _translate = QtCore.QCoreApplication.translate
        Dialog_manage_files.setWindowTitle(_translate("Dialog_manage_files", "Files"))
        self.pushButton_view.setToolTip(_translate("Dialog_manage_files", "<html><head/><body><p>View file</p></body></html>"))
        self.pushButton_create.setToolTip(_translate("Dialog_manage_files", "<html><head/><body><p>Create a text file</p></body></html>"))
        self.pushButton_export.setToolTip(_translate("Dialog_manage_files", "Export selected file.\n"
"Text files (from any source) are exported from the text stored in the database as .txt files.\n"
"(You can open the project folder and copy/paste the orignal text file if preferred.)"))
        self.pushButton_delete.setToolTip(_translate("Dialog_manage_files", "<html><head/><body><p>Select files for deletion</p></body></html>"))
        self.pushButton_import.setToolTip(_translate("Dialog_manage_files", "<html><head/><body><p>Import file into project folder</p></body></html>"))
        self.pushButton_add_attribute.setToolTip(_translate("Dialog_manage_files", "<html><head/><body><p>Add attribute</p></body></html>"))
        self.pushButton_link.setToolTip(_translate("Dialog_manage_files", "<html><head/><body><p>Link to a file that is outside the project folder</p></body></html>"))
        self.pushButton_import_from_linked.setToolTip(_translate("Dialog_manage_files", "<html><head/><body><p>Import linked file into project folder</p></body></html>"))
        self.pushButton_export_to_linked.setToolTip(_translate("Dialog_manage_files", "Export file from project folder as a linked file.\n"
"Cannot export text transcription file associated with an audio or video as a linked file."))
        self.pushButton_export_attributes.setToolTip(_translate("Dialog_manage_files", "<html><head/><body><p>Export attributes to file</p></body></html>"))
        self.pushButton_help.setToolTip(_translate("Dialog_manage_files", "Help"))
        self.label_fcount.setText(_translate("Dialog_manage_files", "Files:"))
        self.pushButton_undo.setToolTip(_translate("Dialog_manage_files", "<html><head/><body><p>Undo file rename</p></body></html>"))
        self.pushButton_bulk_rename.setToolTip(_translate("Dialog_manage_files", "<html><head/><body><p>Bulk rename of database name file entries.</p><p>Only rename visible file rows. Can show only some rows by using attribute selection, or show/hide value like...</p><p>Renamed as: User chosen prefix and numbered suffix _nnn.</p><p>e.g. interview_001</p></body></html>"))
        self.pushButton_display_save.setToolTip(_translate("Dialog_manage_files", "<html><head/><body><p>Save table display settings. </p><p>(Hidden rows and columns and column sizing)</p></body></html>"))
        self.pushButton_display_load.setToolTip(_translate("Dialog_manage_files", "<html><head/><body><p>Load saved table display setting.</p><p>(Hidden rows and columns and column sizing)</p></body></html>"))
        self.pushButton_display_delete.setToolTip(_translate("Dialog_manage_files", "Delete saved table display settings. "))
        self.pushButton_pseudonyms.setToolTip(_translate("Dialog_manage_files", "Pseudonymisation (data de-identfication)\n"
"Before importing text files, create a list of names or phrases to be replaced.\n"
"Applies to these files: docx, epub, htm, html, md, rtf, odt, txt, survey imports of qualitative columns.\n"
"Pseudonym replacements are case sensitive. \n"
"So separate entries would be needed for Tom and TOM.\n"
"\n"
"Does not work with PDF files. Instead extract the plain text and only import the plain text of the PDF.\n"
"\n"
"The pseudonyms are stored in the qda data folder as pseudonyms.json\n"
"After all text files are imported, remove this file from the project folder and store it securely.\n"
""))
        self.label_file.setText(_translate("Dialog_manage_files", "File:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_manage_files = QtWidgets.QDialog()
    ui = Ui_Dialog_manage_files()
    ui.setupUi(Dialog_manage_files)
    Dialog_manage_files.show()
    sys.exit(app.exec())
