# Form implementation generated from reading ui file 'ui_dialog_organiser_assist_split.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogOrganiserAssistSplit(object):
    def setupUi(self, DialogOrganiserAssistSplit):
        DialogOrganiserAssistSplit.setObjectName("DialogOrganiserAssistSplit")
        DialogOrganiserAssistSplit.resize(820, 520)
        self.gridLayout = QtWidgets.QGridLayout(DialogOrganiserAssistSplit)
        self.gridLayout.setObjectName("gridLayout")
        self.label_source = QtWidgets.QLabel(parent=DialogOrganiserAssistSplit)
        self.label_source.setObjectName("label_source")
        self.gridLayout.addWidget(self.label_source, 0, 0, 1, 3)
        self.horizontalLayout_name = QtWidgets.QHBoxLayout()
        self.horizontalLayout_name.setObjectName("horizontalLayout_name")
        self.label_new_name = QtWidgets.QLabel(parent=DialogOrganiserAssistSplit)
        self.label_new_name.setObjectName("label_new_name")
        self.horizontalLayout_name.addWidget(self.label_new_name)
        self.lineEdit_new_name = QtWidgets.QLineEdit(parent=DialogOrganiserAssistSplit)
        self.lineEdit_new_name.setObjectName("lineEdit_new_name")
        self.horizontalLayout_name.addWidget(self.lineEdit_new_name)
        self.gridLayout.addLayout(self.horizontalLayout_name, 1, 0, 1, 3)
        self.label_keep = QtWidgets.QLabel(parent=DialogOrganiserAssistSplit)
        self.label_keep.setObjectName("label_keep")
        self.gridLayout.addWidget(self.label_keep, 2, 0, 1, 1)
        self.label_move = QtWidgets.QLabel(parent=DialogOrganiserAssistSplit)
        self.label_move.setObjectName("label_move")
        self.gridLayout.addWidget(self.label_move, 2, 2, 1, 1)
        self.listWidget_keep = QtWidgets.QListWidget(parent=DialogOrganiserAssistSplit)
        self.listWidget_keep.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.ExtendedSelection)
        self.listWidget_keep.setObjectName("listWidget_keep")
        self.gridLayout.addWidget(self.listWidget_keep, 3, 0, 1, 1)
        self.verticalLayout_buttons = QtWidgets.QVBoxLayout()
        self.verticalLayout_buttons.setObjectName("verticalLayout_buttons")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_buttons.addItem(spacerItem)
        self.pushButton_move = QtWidgets.QPushButton(parent=DialogOrganiserAssistSplit)
        self.pushButton_move.setMinimumSize(QtCore.QSize(40, 32))
        self.pushButton_move.setMaximumSize(QtCore.QSize(40, 32))
        self.pushButton_move.setObjectName("pushButton_move")
        self.verticalLayout_buttons.addWidget(self.pushButton_move)
        self.pushButton_keep = QtWidgets.QPushButton(parent=DialogOrganiserAssistSplit)
        self.pushButton_keep.setMinimumSize(QtCore.QSize(40, 32))
        self.pushButton_keep.setMaximumSize(QtCore.QSize(40, 32))
        self.pushButton_keep.setObjectName("pushButton_keep")
        self.verticalLayout_buttons.addWidget(self.pushButton_keep)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_buttons.addItem(spacerItem1)
        self.pushButton_preview = QtWidgets.QPushButton(parent=DialogOrganiserAssistSplit)
        self.pushButton_preview.setMinimumSize(QtCore.QSize(40, 32))
        self.pushButton_preview.setMaximumSize(QtCore.QSize(40, 32))
        self.pushButton_preview.setText("")
        self.pushButton_preview.setObjectName("pushButton_preview")
        self.verticalLayout_buttons.addWidget(self.pushButton_preview)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_buttons.addItem(spacerItem2)
        self.gridLayout.addLayout(self.verticalLayout_buttons, 3, 1, 1, 1)
        self.listWidget_move = QtWidgets.QListWidget(parent=DialogOrganiserAssistSplit)
        self.listWidget_move.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.ExtendedSelection)
        self.listWidget_move.setObjectName("listWidget_move")
        self.gridLayout.addWidget(self.listWidget_move, 3, 2, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=DialogOrganiserAssistSplit)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 4, 0, 1, 3)

        self.retranslateUi(DialogOrganiserAssistSplit)
        self.buttonBox.accepted.connect(DialogOrganiserAssistSplit.accept) # type: ignore
        self.buttonBox.rejected.connect(DialogOrganiserAssistSplit.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogOrganiserAssistSplit)

    def retranslateUi(self, DialogOrganiserAssistSplit):
        _translate = QtCore.QCoreApplication.translate
        DialogOrganiserAssistSplit.setWindowTitle(_translate("DialogOrganiserAssistSplit", "Split"))
        self.label_source.setText(_translate("DialogOrganiserAssistSplit", "Source:"))
        self.label_new_name.setText(_translate("DialogOrganiserAssistSplit", "Name of the new item:"))
        self.label_keep.setText(_translate("DialogOrganiserAssistSplit", "Stays in the original"))
        self.label_move.setText(_translate("DialogOrganiserAssistSplit", "Moves to the new item"))
        self.pushButton_move.setToolTip(_translate("DialogOrganiserAssistSplit", "<html><head/><body><p>Move selected items to the new item.</p></body></html>"))
        self.pushButton_move.setText(_translate("DialogOrganiserAssistSplit", ">"))
        self.pushButton_keep.setToolTip(_translate("DialogOrganiserAssistSplit", "<html><head/><body><p>Keep selected items in the original.</p></body></html>"))
        self.pushButton_keep.setText(_translate("DialogOrganiserAssistSplit", "<"))
        self.pushButton_preview.setToolTip(_translate("DialogOrganiserAssistSplit", "<html><head/><body><p>View the selected item in context. Double-click on a list item also opens the preview.</p></body></html>"))
