# Form implementation generated from reading ui file 'ui_dialog_graph_picker.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_graph_picker(object):
    def setupUi(self, Dialog_graph_picker):
        Dialog_graph_picker.setObjectName("Dialog_graph_picker")
        Dialog_graph_picker.resize(900, 540)
        Dialog_graph_picker.setSizeGripEnabled(True)
        self.verticalLayout_main = QtWidgets.QVBoxLayout(Dialog_graph_picker)
        self.verticalLayout_main.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_main.setObjectName("verticalLayout_main")
        self.splitter = QtWidgets.QSplitter(parent=Dialog_graph_picker)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.widget_left = QtWidgets.QWidget(parent=self.splitter)
        self.widget_left.setObjectName("widget_left")
        self.verticalLayout_left = QtWidgets.QVBoxLayout(self.widget_left)
        self.verticalLayout_left.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_left.setObjectName("verticalLayout_left")
        self.label_heading = QtWidgets.QLabel(parent=self.widget_left)
        self.label_heading.setObjectName("label_heading")
        self.verticalLayout_left.addWidget(self.label_heading)
        self.horizontalLayout_order = QtWidgets.QHBoxLayout()
        self.horizontalLayout_order.setObjectName("horizontalLayout_order")
        self.label_order = QtWidgets.QLabel(parent=self.widget_left)
        self.label_order.setObjectName("label_order")
        self.horizontalLayout_order.addWidget(self.label_order)
        self.comboBox_order = QtWidgets.QComboBox(parent=self.widget_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_order.sizePolicy().hasHeightForWidth())
        self.comboBox_order.setSizePolicy(sizePolicy)
        self.comboBox_order.setObjectName("comboBox_order")
        self.horizontalLayout_order.addWidget(self.comboBox_order)
        self.verticalLayout_left.addLayout(self.horizontalLayout_order)
        self.listWidget_graphs = QtWidgets.QListWidget(parent=self.widget_left)
        self.listWidget_graphs.setMinimumSize(QtCore.QSize(220, 0))
        self.listWidget_graphs.setAlternatingRowColors(True)
        self.listWidget_graphs.setObjectName("listWidget_graphs")
        self.verticalLayout_left.addWidget(self.listWidget_graphs)
        self.widget_right = QtWidgets.QWidget(parent=self.splitter)
        self.widget_right.setObjectName("widget_right")
        self.verticalLayout_right = QtWidgets.QVBoxLayout(self.widget_right)
        self.verticalLayout_right.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_right.setObjectName("verticalLayout_right")
        self.label_preview = QtWidgets.QLabel(parent=self.widget_right)
        self.label_preview.setObjectName("label_preview")
        self.verticalLayout_right.addWidget(self.label_preview)
        self.graphicsView_preview = QtWidgets.QGraphicsView(parent=self.widget_right)
        self.graphicsView_preview.setMinimumSize(QtCore.QSize(420, 320))
        self.graphicsView_preview.setRenderHints(QtGui.QPainter.RenderHint.Antialiasing|QtGui.QPainter.RenderHint.TextAntialiasing)
        self.graphicsView_preview.setObjectName("graphicsView_preview")
        self.verticalLayout_right.addWidget(self.graphicsView_preview)
        self.label_description = QtWidgets.QLabel(parent=self.widget_right)
        self.label_description.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_description.setFont(font)
        self.label_description.setText("")
        self.label_description.setWordWrap(True)
        self.label_description.setObjectName("label_description")
        self.verticalLayout_right.addWidget(self.label_description)
        self.verticalLayout_main.addWidget(self.splitter)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog_graph_picker)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_main.addWidget(self.buttonBox)

        self.retranslateUi(Dialog_graph_picker)
        QtCore.QMetaObject.connectSlotsByName(Dialog_graph_picker)

    def retranslateUi(self, Dialog_graph_picker):
        _translate = QtCore.QCoreApplication.translate
        Dialog_graph_picker.setWindowTitle(_translate("Dialog_graph_picker", "Graphs"))
        self.label_heading.setText(_translate("Dialog_graph_picker", "Saved graphs:"))
        self.label_order.setText(_translate("Dialog_graph_picker", "Order:"))
        self.comboBox_order.setToolTip(_translate("Dialog_graph_picker", "Sort the graph list"))
        self.label_preview.setText(_translate("Dialog_graph_picker", "Preview:"))
