# Form implementation generated from reading ui file 'ui_dialog_pseudonyms.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_pseudonyms(object):
    def setupUi(self, Dialog_pseudonyms):
        Dialog_pseudonyms.setObjectName("Dialog_pseudonyms")
        Dialog_pseudonyms.resize(759, 534)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_pseudonyms)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=Dialog_pseudonyms)
        self.label.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.groupBox = QtWidgets.QGroupBox(parent=Dialog_pseudonyms)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 40))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 40))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.lineEdit_original = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit_original.setGeometry(QtCore.QRect(50, 7, 321, 30))
        self.lineEdit_original.setObjectName("lineEdit_original")
        self.lineEdit_pseudonym = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit_pseudonym.setGeometry(QtCore.QRect(410, 7, 321, 30))
        self.lineEdit_pseudonym.setObjectName("lineEdit_pseudonym")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(375, 7, 30, 30))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.pushButton_add = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_add.setGeometry(QtCore.QRect(10, 7, 30, 30))
        self.pushButton_add.setText("")
        self.pushButton_add.setObjectName("pushButton_add")
        self.verticalLayout.addWidget(self.groupBox)
        self.tableWidget = QtWidgets.QTableWidget(parent=Dialog_pseudonyms)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog_pseudonyms)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog_pseudonyms)
        self.buttonBox.accepted.connect(Dialog_pseudonyms.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog_pseudonyms.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_pseudonyms)

    def retranslateUi(self, Dialog_pseudonyms):
        _translate = QtCore.QCoreApplication.translate
        Dialog_pseudonyms.setWindowTitle(_translate("Dialog_pseudonyms", "Pseudonyms"))
        self.label.setText(_translate("Dialog_pseudonyms", "Pseudonyms. Data de-identification applied on file import"))
        self.lineEdit_original.setToolTip(_translate("Dialog_pseudonyms", "Original"))
        self.lineEdit_pseudonym.setToolTip(_translate("Dialog_pseudonyms", "Pseudonym"))
        self.pushButton_add.setToolTip(_translate("Dialog_pseudonyms", "Add to pseudonyms"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_pseudonyms = QtWidgets.QDialog()
    ui = Ui_Dialog_pseudonyms()
    ui.setupUi(Dialog_pseudonyms)
    Dialog_pseudonyms.show()
    sys.exit(app.exec())
