# Form implementation generated from reading ui file 'c:\Users\kai\Documents\Programmierung\QualCoderOrig\QualCoder\src\GUI_UIs\ui_dialog_coder_names.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_coders(object):
    def setupUi(self, Dialog_coders):
        Dialog_coders.setObjectName("Dialog_coders")
        Dialog_coders.resize(506, 355)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_coders)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=Dialog_coders)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.table_frame = QtWidgets.QFrame(parent=Dialog_coders)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_frame.sizePolicy().hasHeightForWidth())
        self.table_frame.setSizePolicy(sizePolicy)
        self.table_frame.setMinimumSize(QtCore.QSize(0, 100))
        self.table_frame.setStyleSheet("QFrame#table_frame {\n"
"    background-color: palette(base);\n"
"}")
        self.table_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.table_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.table_frame.setObjectName("table_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.table_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.table_frame)
        self.tableWidget.setToolTip("")
        self.tableWidget.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectItems)
        self.tableWidget.setWordWrap(False)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.widget = QtWidgets.QWidget(parent=self.table_frame)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_add = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_add.setObjectName("pushButton_add")
        self.horizontalLayout.addWidget(self.pushButton_add)
        self.pushButton_rename = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_rename.setObjectName("pushButton_rename")
        self.horizontalLayout.addWidget(self.pushButton_rename)
        self.pushButton_merge = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_merge.setObjectName("pushButton_merge")
        self.horizontalLayout.addWidget(self.pushButton_merge)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.widget)
        self.verticalLayout.addWidget(self.table_frame)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog_coders)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Help|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog_coders)
        self.buttonBox.accepted.connect(Dialog_coders.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog_coders.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_coders)

    def retranslateUi(self, Dialog_coders):
        _translate = QtCore.QCoreApplication.translate
        Dialog_coders.setWindowTitle(_translate("Dialog_coders", "Coders"))
        self.label_2.setText(_translate("Dialog_coders", "Choose (✓) your own coder name and adjust the visibility of others:"))
        self.pushButton_add.setText(_translate("Dialog_coders", "Add"))
        self.pushButton_rename.setText(_translate("Dialog_coders", "Rename"))
        self.pushButton_merge.setText(_translate("Dialog_coders", "Merge"))
