# Form implementation generated from reading ui file 'ui_dialog_SQL.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_sql(object):
    def setupUi(self, Dialog_sql):
        Dialog_sql.setObjectName("Dialog_sql")
        Dialog_sql.resize(900, 590)
        self.gridLayout = QtWidgets.QGridLayout(Dialog_sql)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter_2 = QtWidgets.QSplitter(parent=Dialog_sql)
        self.splitter_2.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.treeWidget = QtWidgets.QTreeWidget(parent=self.splitter_2)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "Tables")
        self.splitter = QtWidgets.QSplitter(parent=self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.splitter.setObjectName("splitter")
        self.textEdit_sql = QtWidgets.QTextEdit(parent=self.splitter)
        self.textEdit_sql.setObjectName("textEdit_sql")
        self.tableWidget_results = QtWidgets.QTableWidget(parent=self.splitter)
        self.tableWidget_results.setObjectName("tableWidget_results")
        self.tableWidget_results.setColumnCount(0)
        self.tableWidget_results.setRowCount(0)
        self.verticalLayout.addWidget(self.splitter_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=Dialog_sql)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.pushButton_runSQL = QtWidgets.QPushButton(parent=Dialog_sql)
        self.pushButton_runSQL.setMinimumSize(QtCore.QSize(32, 32))
        self.pushButton_runSQL.setMaximumSize(QtCore.QSize(32, 32))
        self.pushButton_runSQL.setText("")
        self.pushButton_runSQL.setObjectName("pushButton_runSQL")
        self.horizontalLayout.addWidget(self.pushButton_runSQL)
        self.pushButton_excel = QtWidgets.QPushButton(parent=Dialog_sql)
        self.pushButton_excel.setMinimumSize(QtCore.QSize(32, 32))
        self.pushButton_excel.setMaximumSize(QtCore.QSize(32, 32))
        self.pushButton_excel.setText("")
        self.pushButton_excel.setObjectName("pushButton_excel")
        self.horizontalLayout.addWidget(self.pushButton_excel)
        self.pushButton_csv = QtWidgets.QPushButton(parent=Dialog_sql)
        self.pushButton_csv.setMinimumSize(QtCore.QSize(32, 32))
        self.pushButton_csv.setMaximumSize(QtCore.QSize(32, 32))
        self.pushButton_csv.setText("")
        self.pushButton_csv.setObjectName("pushButton_csv")
        self.horizontalLayout.addWidget(self.pushButton_csv)
        self.comboBox_delimiter = QtWidgets.QComboBox(parent=Dialog_sql)
        self.comboBox_delimiter.setMinimumSize(QtCore.QSize(0, 32))
        self.comboBox_delimiter.setMaximumSize(QtCore.QSize(80, 32))
        self.comboBox_delimiter.setObjectName("comboBox_delimiter")
        self.comboBox_delimiter.addItem("")
        self.comboBox_delimiter.addItem("")
        self.comboBox_delimiter.addItem("")
        self.comboBox_delimiter.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_delimiter)
        self.checkBox_quote = QtWidgets.QCheckBox(parent=Dialog_sql)
        self.checkBox_quote.setMinimumSize(QtCore.QSize(120, 0))
        self.checkBox_quote.setMaximumSize(QtCore.QSize(120, 16777215))
        self.checkBox_quote.setObjectName("checkBox_quote")
        self.horizontalLayout.addWidget(self.checkBox_quote)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog_sql)
        QtCore.QMetaObject.connectSlotsByName(Dialog_sql)

    def retranslateUi(self, Dialog_sql):
        _translate = QtCore.QCoreApplication.translate
        Dialog_sql.setWindowTitle(_translate("Dialog_sql", "SQL_statements"))
        self.label.setText(_translate("Dialog_sql", "SQL reports"))
        self.pushButton_runSQL.setToolTip(_translate("Dialog_sql", "<html><head/><body><p>Run</p></body></html>"))
        self.pushButton_excel.setToolTip(_translate("Dialog_sql", "<html><head/><body><p>Export to Excel</p></body></html>"))
        self.pushButton_csv.setToolTip(_translate("Dialog_sql", "<html><head/><body><p>Export to CSV file</p></body></html>"))
        self.comboBox_delimiter.setToolTip(_translate("Dialog_sql", "<html><head/><body><p>Delimiter for export</p></body></html>"))
        self.comboBox_delimiter.setItemText(0, _translate("Dialog_sql", "tab"))
        self.comboBox_delimiter.setItemText(1, _translate("Dialog_sql", ","))
        self.comboBox_delimiter.setItemText(2, _translate("Dialog_sql", ";"))
        self.comboBox_delimiter.setItemText(3, _translate("Dialog_sql", "|"))
        self.checkBox_quote.setToolTip(_translate("Dialog_sql", "All fields quoted with quotation marks."))
        self.checkBox_quote.setText(_translate("Dialog_sql", "Quote"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_sql = QtWidgets.QDialog()
    ui = Ui_Dialog_sql()
    ui.setupUi(Dialog_sql)
    Dialog_sql.show()
    sys.exit(app.exec())
