# Form implementation generated from reading ui file '/home/qwerty/Bureau/QualCoder/src/GUI_UIs/ui_dialog_code_image.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_code_image(object):
    def setupUi(self, Dialog_code_image):
        Dialog_code_image.setObjectName("Dialog_code_image")
        Dialog_code_image.resize(950, 663)
        self.gridLayout = QtWidgets.QGridLayout(Dialog_code_image)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=Dialog_code_image)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 90))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 90))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_image = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_image.setGeometry(QtCore.QRect(3, 41, 201, 41))
        self.label_image.setWordWrap(True)
        self.label_image.setObjectName("label_image")
        self.label_coded_area = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_coded_area.setGeometry(QtCore.QRect(470, 0, 461, 41))
        self.label_coded_area.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_coded_area.setWordWrap(True)
        self.label_coded_area.setObjectName("label_coded_area")
        self.line = QtWidgets.QFrame(parent=self.groupBox_2)
        self.line.setGeometry(QtCore.QRect(460, 0, 3, 68))
