# Form implementation generated from reading ui file 'c:\Users\kai\Documents\Programmierung\QualCoderOrig\QualCoder\src\GUI_UIs\ui_dialog_speakers.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_speakers(object):
    def setupUi(self, Dialog_speakers):
        Dialog_speakers.setObjectName("Dialog_speakers")
        Dialog_speakers.resize(664, 499)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_speakers)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=Dialog_speakers)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 50))
        self.label.setMaximumSize(QtCore.QSize(16777215, 500))
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tableWidget = QtWidgets.QTableWidget(parent=Dialog_speakers)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectItems)
        self.tableWidget.setWordWrap(False)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tableWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog_speakers)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Help|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog_speakers)
        self.buttonBox.accepted.connect(Dialog_speakers.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog_speakers.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_speakers)

    def retranslateUi(self, Dialog_speakers):
        _translate = QtCore.QCoreApplication.translate
        Dialog_speakers.setWindowTitle(_translate("Dialog_speakers", "Mark Speakers"))
        self.label.setText(_translate("Dialog_speakers", "The following speaker names were detected in the document. \n"
"Select (✓) the ones you want to mark. Clicking OK creates a code for each selected speaker in the “📌 Speakers” category and assigns all corresponding text segments. Doubleclick to edit the \"code as\" name in the table. To merge two speakers (e.g. to correct a typo), rename the \"code as\" in one entry so that it exactly matches the other."))
        self.tableWidget.setToolTip(_translate("Dialog_speakers", "Doubleclick a \"coded as\" name to edit"))
