# Form implementation generated from reading ui file 'ui_dialog_speakers.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_speakers(object):
    def setupUi(self, Dialog_speakers):
        Dialog_speakers.setObjectName("Dialog_speakers")
        Dialog_speakers.resize(680, 470)
        Dialog_speakers.setMinimumSize(QtCore.QSize(560, 360))
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_speakers)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_top = QtWidgets.QHBoxLayout()
        self.horizontalLayout_top.setObjectName("horizontalLayout_top")
        self.label_identifier = QtWidgets.QLabel(parent=Dialog_speakers)
        self.label_identifier.setObjectName("label_identifier")
        self.horizontalLayout_top.addWidget(self.label_identifier)
        self.comboBox_identifier = QtWidgets.QComboBox(parent=Dialog_speakers)
        self.comboBox_identifier.setObjectName("comboBox_identifier")
        self.horizontalLayout_top.addWidget(self.comboBox_identifier)
        self.lineEdit_custom = QtWidgets.QLineEdit(parent=Dialog_speakers)
        self.lineEdit_custom.setMinimumSize(QtCore.QSize(170, 0))
        self.lineEdit_custom.setObjectName("lineEdit_custom")
        self.horizontalLayout_top.addWidget(self.lineEdit_custom)
        self.pushButton_select_files = QtWidgets.QPushButton(parent=Dialog_speakers)
        self.pushButton_select_files.setObjectName("pushButton_select_files")
        self.horizontalLayout_top.addWidget(self.pushButton_select_files)
        spacerItem = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_top.addItem(spacerItem)
        self.pushButton_help = QtWidgets.QPushButton(parent=Dialog_speakers)
        self.pushButton_help.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_help.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_help.setText("")
        self.pushButton_help.setObjectName("pushButton_help")
        self.horizontalLayout_top.addWidget(self.pushButton_help)
        self.verticalLayout.addLayout(self.horizontalLayout_top)
        self.label_info = QtWidgets.QLabel(parent=Dialog_speakers)
        self.label_info.setText("")
        self.label_info.setObjectName("label_info")
        self.verticalLayout.addWidget(self.label_info)
        self.horizontalLayout_options = QtWidgets.QHBoxLayout()
        self.horizontalLayout_options.setObjectName("horizontalLayout_options")
        self.label = QtWidgets.QLabel(parent=Dialog_speakers)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.horizontalLayout_options.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout_options)
        self.checkBox_include_name = QtWidgets.QCheckBox(parent=Dialog_speakers)
        self.checkBox_include_name.setChecked(False)
        self.checkBox_include_name.setObjectName("checkBox_include_name")
        self.verticalLayout.addWidget(self.checkBox_include_name)
        self.tableWidget = QtWidgets.QTableWidget(parent=Dialog_speakers)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectItems)
        self.tableWidget.setWordWrap(False)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tableWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog_speakers)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog_speakers)
        self.buttonBox.accepted.connect(Dialog_speakers.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog_speakers.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_speakers)

    def retranslateUi(self, Dialog_speakers):
        _translate = QtCore.QCoreApplication.translate
        Dialog_speakers.setWindowTitle(_translate("Dialog_speakers", "Mark Speakers"))
        self.label_identifier.setText(_translate("Dialog_speakers", "Identifier:"))
        self.comboBox_identifier.setToolTip(_translate("Dialog_speakers", "How each speaker is marked at the start of a line: Name: , #Name: , @Name: , [Name] , {Name} , or a custom pattern. Auto-detect picks the format with the most turns."))
        self.lineEdit_custom.setToolTip(_translate("Dialog_speakers", "Custom regular expression. It must contain one capture group for the speaker name. Example: ^\\s*>>\\s*(.+?):"))
        self.lineEdit_custom.setPlaceholderText(_translate("Dialog_speakers", "regex with one group, e.g. ^\\s*(.+?):"))
        self.pushButton_select_files.setToolTip(_translate("Dialog_speakers", "Choose which text files to scan for speakers. You can mark speakers across several files at once."))
        self.pushButton_select_files.setText(_translate("Dialog_speakers", "Select files"))
        self.pushButton_help.setToolTip(_translate("Dialog_speakers", "Help"))
        self.label_info.setToolTip(_translate("Dialog_speakers", "Number of speakers and turns detected with the current identifier and files."))
        self.label.setToolTip(_translate("Dialog_speakers", "Double-click a \"code as\" cell to rename a speaker. Give two rows the same \"code as\" to merge them, for example to fix a typo."))
        self.label.setText(_translate("Dialog_speakers", "Tick the speakers to mark. OK creates a code for each one in the “📌 Speakers” category and codes their turns."))
        self.checkBox_include_name.setToolTip(_translate("Dialog_speakers", "Code the whole turn including the speaker label. Uncheck to code only the response text, without the name."))
        self.checkBox_include_name.setText(_translate("Dialog_speakers", "Include speaker name"))
        self.tableWidget.setToolTip(_translate("Dialog_speakers", "Doubleclick a \"code as\" name to edit"))
