# Form implementation generated from reading ui file 'ui_dialog_report_comparisons.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_reportComparisons(object):
    def setupUi(self, Dialog_reportComparisons):
        Dialog_reportComparisons.setObjectName("Dialog_reportComparisons")
        Dialog_reportComparisons.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        Dialog_reportComparisons.resize(804, 606)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_reportComparisons)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=Dialog_reportComparisons)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 100))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 100))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.pushButton_export = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_export.setGeometry(QtCore.QRect(400, 27, 32, 32))
        self.pushButton_export.setText("")
        self.pushButton_export.setObjectName("pushButton_export")
        self.pushButton_run = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_run.setGeometry(QtCore.QRect(320, 27, 32, 32))
        self.pushButton_run.setText("")
        self.pushButton_run.setObjectName("pushButton_run")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 71, 22))
        self.label_2.setObjectName("label_2")
        self.comboBox_coders = QtWidgets.QComboBox(parent=self.groupBox)
        self.comboBox_coders.setGeometry(QtCore.QRect(90, 27, 221, 32))
        self.comboBox_coders.setObjectName("comboBox_coders")
        self.pushButton_clear = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_clear.setGeometry(QtCore.QRect(360, 27, 32, 32))
        self.pushButton_clear.setText("")
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.label_title = QtWidgets.QLabel(parent=self.groupBox)
        self.label_title.setGeometry(QtCore.QRect(10, 0, 491, 22))
        self.label_title.setObjectName("label_title")
        self.label_selections = QtWidgets.QLabel(parent=self.groupBox)
        self.label_selections.setGeometry(QtCore.QRect(10, 60, 751, 32))
        self.label_selections.setMinimumSize(QtCore.QSize(0, 32))
        self.label_selections.setMaximumSize(QtCore.QSize(16777213, 32))
        self.label_selections.setWordWrap(True)
        self.label_selections.setObjectName("label_selections")
        self.pushButton_help1 = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_help1.setGeometry(QtCore.QRect(440, 27, 32, 32))
        self.pushButton_help1.setText("")
        self.pushButton_help1.setObjectName("pushButton_help1")
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=Dialog_reportComparisons)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setContentsMargins(1, 1, 1, 1)
        self.gridLayout.setVerticalSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.treeWidget = QtWidgets.QTreeWidget(parent=self.groupBox_2)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.gridLayout.addWidget(self.treeWidget, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)

        self.retranslateUi(Dialog_reportComparisons)
        QtCore.QMetaObject.connectSlotsByName(Dialog_reportComparisons)
        Dialog_reportComparisons.setTabOrder(self.comboBox_coders, self.pushButton_run)
        Dialog_reportComparisons.setTabOrder(self.pushButton_run, self.pushButton_clear)
        Dialog_reportComparisons.setTabOrder(self.pushButton_clear, self.pushButton_export)
        Dialog_reportComparisons.setTabOrder(self.pushButton_export, self.pushButton_help1)
        Dialog_reportComparisons.setTabOrder(self.pushButton_help1, self.treeWidget)

    def retranslateUi(self, Dialog_reportComparisons):
        _translate = QtCore.QCoreApplication.translate
        Dialog_reportComparisons.setWindowTitle(_translate("Dialog_reportComparisons", "Coder Comparisons"))
        self.pushButton_export.setToolTip(_translate("Dialog_reportComparisons", "<html><head/><body><p>Export Excel</p></body></html>"))
        self.pushButton_run.setToolTip(_translate("Dialog_reportComparisons", "<html><head/><body><p>Run comparison</p></body></html>"))
        self.label_2.setText(_translate("Dialog_reportComparisons", "Coders:"))
        self.comboBox_coders.setToolTip(_translate("Dialog_reportComparisons", "<html><head/><body><p>Select two coders</p></body></html>"))
        self.pushButton_clear.setToolTip(_translate("Dialog_reportComparisons", "<html><head/><body><p>Clear selection</p></body></html>"))
        self.label_title.setText(_translate("Dialog_reportComparisons", "Coder comparisons - text files"))
        self.label_selections.setText(_translate("Dialog_reportComparisons", "Coders selected:"))
        self.pushButton_help1.setToolTip(_translate("Dialog_reportComparisons", "Statistics help"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_reportComparisons = QtWidgets.QDialog()
    ui = Ui_Dialog_reportComparisons()
    ui.setupUi(Dialog_reportComparisons)
    Dialog_reportComparisons.show()
    sys.exit(app.exec())
