# Form implementation generated from reading ui file 'ui_dialog_refi_export_endings.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_refi_export_line_endings(object):
    def setupUi(self, Dialog_refi_export_line_endings):
        Dialog_refi_export_line_endings.setObjectName("Dialog_refi_export_line_endings")
        Dialog_refi_export_line_endings.resize(582, 223)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_refi_export_line_endings)
        self.buttonBox.setGeometry(QtCore.QRect(270, 170, 261, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.radioButton_no_change = QtWidgets.QRadioButton(Dialog_refi_export_line_endings)
        self.radioButton_no_change.setGeometry(QtCore.QRect(30, 100, 431, 23))
        self.radioButton_no_change.setChecked(True)
        self.radioButton_no_change.setObjectName("radioButton_no_change")
        self.radioButton_maxqda = QtWidgets.QRadioButton(Dialog_refi_export_line_endings)
        self.radioButton_maxqda.setGeometry(QtCore.QRect(30, 130, 481, 23))
        self.radioButton_maxqda.setObjectName("radioButton_maxqda")
        self.label = QtWidgets.QLabel(Dialog_refi_export_line_endings)
        self.label.setGeometry(QtCore.QRect(20, 20, 541, 71))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog_refi_export_line_endings)
        self.buttonBox.accepted.connect(Dialog_refi_export_line_endings.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog_refi_export_line_endings.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_refi_export_line_endings)

    def retranslateUi(self, Dialog_refi_export_line_endings):
        _translate = QtCore.QCoreApplication.translate
        Dialog_refi_export_line_endings.setWindowTitle(_translate("Dialog_refi_export_line_endings", "Settings"))
        self.radioButton_no_change.setText(_translate("Dialog_refi_export_line_endings", "No change to line endings"))
        self.radioButton_maxqda.setText(_translate("Dialog_refi_export_line_endings", "Add line ending character for MAXQDA importation"))
        self.label.setText(_translate("Dialog_refi_export_line_endings", "REFI-QDA project export. Plain text representation may need adjustment of line endings so that codes do not shift on import into other software."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_refi_export_line_endings = QtWidgets.QDialog()
    ui = Ui_Dialog_refi_export_line_endings()
    ui.setupUi(Dialog_refi_export_line_endings)
    Dialog_refi_export_line_endings.show()
    sys.exit(app.exec())
