# Form implementation generated from reading ui file 'ui_edit_text.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_edit_text(object):
    def setupUi(self, Dialog_edit_text):
        Dialog_edit_text.setObjectName("Dialog_edit_text")
        Dialog_edit_text.resize(700, 520)
        self.gridLayout = QtWidgets.QGridLayout(Dialog_edit_text)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=Dialog_edit_text)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 30))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 30))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=self.groupBox)
        self.buttonBox.setGeometry(QtCore.QRect(450, 0, 221, 26))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.pushButton_clear = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_clear.setGeometry(QtCore.QRect(370, 0, 89, 26))
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.label_case_sensitive = QtWidgets.QLabel(parent=self.groupBox)
        self.label_case_sensitive.setGeometry(QtCore.QRect(30, 1, 28, 28))
        self.label_case_sensitive.setMinimumSize(QtCore.QSize(28, 28))
        self.label_case_sensitive.setMaximumSize(QtCore.QSize(28, 28))
        self.label_case_sensitive.setText("")
        self.label_case_sensitive.setObjectName("label_case_sensitive")
        self.pushButton_previous = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_previous.setGeometry(QtCore.QRect(230, 0, 28, 28))
        self.pushButton_previous.setText("")
        self.pushButton_previous.setObjectName("pushButton_previous")
        self.checkBox_case_sensitive = QtWidgets.QCheckBox(parent=self.groupBox)
        self.checkBox_case_sensitive.setGeometry(QtCore.QRect(8, 4, 21, 24))
        self.checkBox_case_sensitive.setText("")
        self.checkBox_case_sensitive.setObjectName("checkBox_case_sensitive")
        self.lineEdit_search = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit_search.setGeometry(QtCore.QRect(66, 0, 161, 28))
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.pushButton_next = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_next.setGeometry(QtCore.QRect(260, 0, 28, 28))
        self.pushButton_next.setText("")
        self.pushButton_next.setObjectName("pushButton_next")
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=Dialog_edit_text)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=Dialog_edit_text)
        self.label.setMinimumSize(QtCore.QSize(0, 76))
        self.label.setMaximumSize(QtCore.QSize(16777215, 76))
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)

        self.retranslateUi(Dialog_edit_text)
        self.buttonBox.accepted.connect(Dialog_edit_text.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog_edit_text.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_edit_text)

    def retranslateUi(self, Dialog_edit_text):
        _translate = QtCore.QCoreApplication.translate
        Dialog_edit_text.setWindowTitle(_translate("Dialog_edit_text", "Memo"))
        self.pushButton_clear.setText(_translate("Dialog_edit_text", "Clear"))
        self.label_case_sensitive.setToolTip(_translate("Dialog_edit_text", "Case sensitive"))
        self.pushButton_previous.setToolTip(_translate("Dialog_edit_text", "Previous"))
        self.checkBox_case_sensitive.setToolTip(_translate("Dialog_edit_text", "Case sensitive"))
        self.lineEdit_search.setToolTip(_translate("Dialog_edit_text", "Search for text."))
        self.pushButton_next.setToolTip(_translate("Dialog_edit_text", "Next"))
        self.label.setText(_translate("Dialog_edit_text", "When editing text: Avoid selecting text combinations of unmarked text sections and coded/annotated/case-assigned sections.\n"
"Positions may not correctly adjust. Make  a backup copy of the project before editing text.\n"
""))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_edit_text = QtWidgets.QDialog()
    ui = Ui_Dialog_edit_text()
    ui.setupUi(Dialog_edit_text)
    Dialog_edit_text.show()
    sys.exit(app.exec())
