# Form implementation generated from reading ui file 'C:\Users\salom\Downloads\r6\_ui_backup_20260826_012531\ui_reference_editor.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogReferenceEditor(object):
    def setupUi(self, DialogReferenceEditor):
        DialogReferenceEditor.setObjectName("DialogReferenceEditor")
        DialogReferenceEditor.resize(701, 415)
        self.gridLayout = QtWidgets.QGridLayout(DialogReferenceEditor)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(parent=DialogReferenceEditor)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=DialogReferenceEditor)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(DialogReferenceEditor)
        self.buttonBox.accepted.connect(DialogReferenceEditor.accept) # type: ignore
        self.buttonBox.rejected.connect(DialogReferenceEditor.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogReferenceEditor)

    def retranslateUi(self, DialogReferenceEditor):
        _translate = QtCore.QCoreApplication.translate
        DialogReferenceEditor.setWindowTitle(_translate("DialogReferenceEditor", "Reference Editor"))
